import type { Passage, Question } from './types'

type Item = Omit<Question, 'id' | 'part' | 'passageId' | 'stem' | 'choices'> & {
  stem?: string
  choices: [string, string, string, string]
}
type Seed = Pick<Passage, 'id' | 'part' | 'kind' | 'title' | 'body'> & { questions: Item[] }

// Original practice: connected paragraphs, plausible distractors, and evidence across documents.
const seeds: Seed[] = [
  {
    id:'v9-p6-01',part:6,kind:'email',title:'Supplier Inspection — Revised Delivery Procedure',
    body:`To: Purchasing and Warehouse Teams
From: Dana Cole, Operations Manager
Subject: Revised procedure for incoming equipment

Following last month's review of damaged shipments, we have agreed with our main supplier to inspect all equipment before it leaves the factory. The first inspection under the new arrangement [1] _____ for October 14, two days before our next delivery. A warehouse representative will attend remotely and compare the equipment with the specifications attached to each purchase order.

This additional check should reduce the number of returns. [2] _____, it does not replace the inspection carried out when a shipment reaches our warehouse. Staff must continue recording the condition of the packaging before signing the delivery receipt. If a problem is discovered, the photographs and order number should be sent to Purchasing rather than directly to the driver.

The supplier has asked us to [3] _____ a single contact person for each delivery so that inspection reports reach the right team. Please send me the name of your department's contact by Thursday afternoon. [4] _____ The updated list will then be included in the supplier's confirmation email, which is normally issued the following morning.`,
    questions:[
      {choices:['has scheduled','is scheduled','scheduling','schedule'],answer:'B',skills:['passive','verb-tense'],difficulty:3,ruleId:'p6.passive-tense',explanation:'The inspection receives the scheduling action; the date is an existing arrangement, so is scheduled fits.',explanationTh:'inspection เป็นสิ่งที่ถูกกำหนดวันไว้ ใช้ passive: is scheduled for + วัน',whyOthers:{A:'The inspection does not schedule another event; active has scheduled needs an object.',C:'Scheduling cannot be the finite verb here.',D:'Schedule does not agree with the singular subject and changes the meaning.'}},
      {choices:['Consequently','Similarly','Nevertheless','For instance'],answer:'C',skills:['context','conjunction'],difficulty:4,ruleId:'p6.connector-context',explanation:'The factory check is useful, but the warehouse check remains necessary; nevertheless marks this limitation.',explanationTh:'ตรวจที่โรงงานช่วยลดการคืนสินค้า แต่ยังต้องตรวจที่คลังอยู่ ความสัมพันธ์เป็นข้อจำกัด/ขัดแย้ง ใช้ Nevertheless',whyOthers:{A:'The warehouse inspection is not a consequence of fewer returns.',B:'The next sentence limits the benefit rather than describing a similar action.',D:'It does not give an example of a return.'}},
      {choices:['designate','notify','consult','authorize'],answer:'A',skills:['vocabulary','collocation'],difficulty:4,ruleId:'p6.fixed-phrase',explanation:'Designate a contact person means appoint someone to handle communication; the next sentence requests that person’s name.',explanationTh:'designate a contact person = แต่งตั้งผู้ประสานงาน ดูประโยคถัดไปที่ขอชื่อคนนี้ยืนยันความหมาย',whyOthers:{B:'Notify means tell an existing person something, not appoint a contact.',C:'Consult means ask a person for advice.',D:'Authorize means grant permission; the request is to identify a contact.'}},
      {choices:['The driver will submit the photographs after arriving at the warehouse.','Future inspections will be canceled once the contact list is complete.','Each department may use a different delivery address for its orders.','If that person will be away, include the name of someone who can act in their place.'],answer:'D',skills:['sentence-placement','context'],difficulty:5,ruleId:'p6.sentence-placement',explanation:'That person refers to the nominated contact; providing a substitute belongs before the completed list is sent to the supplier.',explanationTh:'that person เชื่อมกับ contact person และให้ใส่ชื่อคนสำรองก่อนส่ง updated list ตัวลวงอื่นเปลี่ยนขั้นตอนหรือเพิ่มเงื่อนไขที่ไม่มี',whyOthers:{A:'Warehouse staff, not the driver, submit the photographs.',B:'The inspections continue; appointing contacts does not cancel them.',C:'Delivery addresses are not the subject of the contact list.'}},
    ],
  },
  {
    id:'v9-p6-02',part:6,kind:'notice',title:'Renovation Access for Library Members',
    body:`WESTHAVEN PUBLIC LIBRARY
Temporary entrance and collection arrangements

Renovation of our main entrance will begin on Monday, November 2, and is expected to take three weeks. During this period, visitors should enter through the courtyard gate on Pine Street. The gate is step-free, but the pathway is narrower than the main entrance, so please allow extra time when attending a scheduled event. All reading rooms will remain open at their usual hours.

Books reserved online will be available for [1] _____ at a temporary desk beside the courtyard entrance. Members will receive an email when their items are ready; please wait for this message before making a special trip. [2] _____ The notice will include the date after which uncollected items are returned to the shelves.

The outdoor return box on Market Road will be inaccessible while the builders are working. [3] _____ returning items there, use the box inside the courtyard gate, which will be accessible even when the reading rooms are closed. Loan periods will not be extended automatically.

If the construction causes an unexpected closure, a revised notice [4] _____ on our website and sent to members registered for activities that day. Please check the website before traveling, especially during the first week of work.`,
    questions:[
      {choices:['collect','collection','collective','collected'],answer:'B',skills:['part-of-speech'],difficulty:3,ruleId:'p6.word-form',explanation:'Available for collection is the noun phrase meaning ready to be picked up.',explanationTh:'available for + นาม ใช้ collection = การรับหนังสือ ไม่ใช่รูปกริยา collect',whyOthers:{A:'A base verb cannot follow for here.',C:'Collective is an adjective, and no noun follows it here.',D:'Collected is a participle, not the required noun.'}},
      {choices:['Messages will be sent only after an item has been placed at the temporary desk.','Members should return all reserved books before the renovation starts.','The permanent collection desk will reopen next Monday.','Reserved items will remain available until the renovation is complete.'],answer:'A',skills:['sentence-placement','context'],difficulty:4,ruleId:'p6.sentence-placement',explanation:'The inserted sentence clarifies when the readiness email is sent, and the following sentence continues describing that notice.',explanationTh:'ประโยคก่อนให้รอ email ว่าหนังสือพร้อม จึงต่อด้วยเงื่อนไขการส่งข้อความ แล้ว The notice ในประโยคถัดไปยังหมายถึงข้อความเดิม',whyOthers:{B:'The notice does not require reserved books to be returned before construction.',C:'The renovation lasts three weeks, not just until next Monday.',D:'The next sentence specifies an individual collection deadline, not the end of renovation.'}},
      {choices:['In addition to','Because of','Instead of','Despite'],answer:'C',skills:['preposition','context'],difficulty:4,ruleId:'p6.connector-context',explanation:'The inaccessible box must be replaced by the courtyard box; instead of introduces the action to avoid.',explanationTh:'กล่องเดิมใช้ไม่ได้ จึงต้องใช้กล่องใหม่แทน ใช้ Instead of + V-ing ไม่ใช่เพิ่มอีกช่องทาง',whyOthers:{A:'In addition to suggests both boxes can be used.',B:'Because of gives a reason, not a replacement action.',D:'Despite expresses concession, not an alternative return location.'}},
      {choices:['will post','has posted','posting','will be posted'],answer:'D',skills:['passive','verb-tense'],difficulty:3,ruleId:'p6.passive-tense',explanation:'A future notice receives the action of posting after a possible closure, so will be posted fits.',explanationTh:'notice ถูกโพสต์ในอนาคตถ้ามีเหตุปิด ใช้ will be posted ไม่ใช่ notice โพสต์เอง',whyOthers:{A:'A notice cannot actively post another item here.',B:'Has posted wrongly treats the notice as the agent and describes a completed action.',C:'Posting alone cannot complete this future conditional statement.'}},
    ],
  },
  {
    id:'v9-p6-03',part:6,kind:'email',title:'Expense Claims for the Regional Meeting',
    body:`To: Regional Meeting Participants
From: Accounting Services
Subject: Travel expense submission deadline

Thank you for attending last week's regional meeting. We are now processing travel expenses for employees who were asked to attend in person. To ensure that reimbursement appears in this month's payment cycle, please submit the completed claim form and supporting receipts by October 9. Claims received later will still be reviewed, but payment may be delayed until the following month.

When completing the form, enter accommodation and local transportation costs [1] _____ rather than combining them in one total. This allows us to compare each category with the relevant spending limit. [2] _____, a missing receipt does not automatically make an expense ineligible: explain the reason for its absence and attach another record of payment if available.

Employees whose hotel bookings [3] _____ directly by the company should not list the room charge as a personal expense. Any meals paid for separately may still be claimed, provided that they fall within the daily allowance. Please note that the allowance applies to the day of the meeting as well as approved travel days.

[4] _____ Your manager must confirm the business purpose of the trip before Accounting can authorize payment, even if all of the receipts are complete.`,
    questions:[
      {choices:['separate','separation','separately','separating'],answer:'C',skills:['part-of-speech'],difficulty:3,ruleId:'p6.word-form',explanation:'Separately modifies enter and is contrasted with combining the costs in one total.',explanationTh:'ช่องนี้ขยาย enter ว่าให้ลงรายการอย่างไร ใช้ separately และ rather than combining ยืนยันว่าต้องแยกหมวด',whyOthers:{A:'Separate is an adjective, not the adverb modifying enter.',B:'Separation is a noun and cannot modify the action directly.',D:'Separating would require a different sentence structure.'}},
      {choices:['Accordingly','However','For example','Otherwise'],answer:'B',skills:['context','conjunction'],difficulty:4,ruleId:'p6.connector-context',explanation:'Supporting receipts are normally required, but the next sentence introduces an exception for a missing receipt.',explanationTh:'ต้นอีเมลขอ supporting receipts แต่ตรงนี้เปิดข้อยกเว้นว่าใบเสร็จหายยังเบิกได้ จึงใช้ However',whyOthers:{A:'The exception is not a result of separating expense categories.',C:'The missing-receipt policy is not an example of a spending category.',D:'Otherwise would introduce the consequence of failing to separate costs.'}},
      {choices:['were paid for','have paid for','are paying','pay'],answer:'A',skills:['passive','verb-tense'],difficulty:4,ruleId:'p6.passive-tense',explanation:'The bookings were paid for by the company; last week’s completed meeting establishes the past context.',explanationTh:'bookings เป็นรายการที่บริษัทจ่ายให้แล้วในทริปสัปดาห์ก่อน ใช้ were paid for + by the company',whyOthers:{B:'The bookings cannot perform the payment themselves.',C:'Are paying makes the bookings the agent and implies an ongoing payment.',D:'Pay is active and does not describe the company paying for bookings.'}},
      {choices:['Accounting will pay all claims before a manager reviews them.','Employees may omit the meeting date when all receipts are attached.','The daily meal allowance also covers unapproved vacation days.','Before sending the documents to us, forward the claim to your manager for approval.'],answer:'D',skills:['sentence-placement','context'],difficulty:5,ruleId:'p6.sentence-placement',explanation:'The following sentence explains why manager approval must precede Accounting authorization.',explanationTh:'ประโยคถัดไปบอก Your manager must confirm ... before Accounting จึงต้องส่งให้หัวหน้าอนุมัติก่อน ไม่ใช่จ่ายก่อนตรวจ',whyOthers:{A:'It reverses the explicit approval sequence.',B:'Complete receipts do not waive the business-purpose requirement.',C:'Only approved travel days are eligible; vacation days are not mentioned.'}},
    ],
  },
  {
    id:'v9-p6-04',part:6,kind:'advertisement',title:'Retail Data Workshop — Registration Conditions',
    body:`HARBOR BUSINESS INSTITUTE
Using Retail Data to Plan Inventory
Friday, November 20, 9:00 A.M.–4:30 P.M.

This practical workshop is designed for store managers who already maintain basic sales records but want to use them more effectively. Participants will compare several forecasting methods and identify situations in which a simple weekly average can produce misleading results. The morning activities [1] _____ on sales patterns; the afternoon session will apply those patterns to purchasing decisions.

Participants should bring a laptop and an anonymized sales file containing at least eight weeks of data. Sample files will be provided for anyone unable to bring company records. These files contain [2] _____ data created specifically for the exercises, rather than records taken from operating stores. The instructor will demonstrate the same calculations with the supplied files, so no one will be excluded from the practical exercises.

The fee includes course materials and lunch but not parking. A ten-percent discount is available for registrations [3] _____ before November 6. After that date, places may still be booked at the full fee, subject to availability.

If you cannot attend, you may nominate a colleague to take your place by contacting us at least two business days before the workshop. [4] _____ This policy enables us to prepare the participant list without leaving a paid place unused.`,
    questions:[
      {choices:['will focus','focused','has focused','focusing'],answer:'A',skills:['verb-tense','subject-verb'],difficulty:3,ruleId:'p6.verb-tense',explanation:'The workshop has not occurred yet; plural activities will focus on the planned topic.',explanationTh:'เป็นกำหนดการอบรมในอนาคตและประธาน activities เป็นพหูพจน์ ใช้ will focus',whyOthers:{B:'Focused places a planned future workshop in the past.',C:'Has focused does not agree with activities and describes a completed action.',D:'Focusing lacks a finite auxiliary.'}},
      {choices:['historical','simulated','confidential','reconciled'],answer:'B',skills:['vocabulary','context'],difficulty:4,ruleId:'p6.fixed-phrase',explanation:'Simulated data is created for practice rather than taken from real stores; the whole sentence supplies that contrast.',explanationTh:'simulated data = ข้อมูลจำลอง ดู created specifically for exercises และ rather than records taken from operating stores ยืนยันว่าไม่ได้ใช้ข้อมูลร้านจริง',whyOthers:{A:'Historical data would be records of past real activity, which the sentence contrasts with these files.',C:'Confidential describes access restrictions, not data created for exercises.',D:'Reconciled means checked for agreement between records; no such comparison is described.'}},
      {choices:['completes','completion','completed','completing'],answer:'C',skills:['passive','part-of-speech'],difficulty:4,ruleId:'p6.word-form',explanation:'Completed before November 6 is a reduced passive clause modifying registrations.',explanationTh:'registrations ที่ถูกทำเสร็จก่อนวันกำหนด ใช้ completed เป็น reduced passive ขยายนาม',whyOthers:{A:'Completes is a singular finite verb, not a passive modifier of plural registrations.',B:'Completion is a noun that cannot directly modify registrations in this position.',D:'Completing would make registrations perform an action.'}},
      {choices:['The colleague must pay the entire course fee again.','All paid registrations will be refunded automatically after the deadline.','The change must be requested on the morning of the workshop.','No additional fee is charged for transferring the registration in this way.'],answer:'D',skills:['sentence-placement','context'],difficulty:5,ruleId:'p6.sentence-placement',explanation:'In this way links to nominating a replacement; a fee-free transfer prevents an already paid place being wasted.',explanationTh:'in this way เชื่อมกับการให้เพื่อนร่วมงานมาแทน และ this policy ถัดไปอธิบายการรักษาที่นั่งที่จ่ายแล้ว จึงต่อด้วยเงื่อนไขโอนสิทธิ์ฟรี',whyOthers:{A:'Charging the entire fee again would not describe a transfer of the paid place.',B:'The paragraph is about substitution, not automatic refunds.',C:'The explicit deadline is at least two business days before the event.'}},
    ],
  },
  {
    id:'v9-p6-05',part:6,kind:'email',title:'Remote Access Trial — Feedback and Eligibility',
    body:`To: Department Supervisors
From: Information Services
Subject: Second phase of remote access trial

The first phase of our remote access trial ended last Friday. Employees in the customer support team reported that they could retrieve shared documents more quickly, although some experienced difficulty connecting from older laptops. We have since adjusted the login process and will begin a second trial with the finance and purchasing teams on October 19.

Supervisors should [1] _____ the names of employees who need access from outside the office. Please include the type of device each person normally uses. [2] _____ This will allow technicians to prepare the appropriate instructions before the trial begins, rather than resolving every issue on the first day.

Access will initially be limited to shared documents; the payroll application will remain available only on office computers. [3] _____ the second trial produces satisfactory results, we will review whether other applications can be added. Employees should not assume that permission to view documents includes permission to download customer records.

Participants will receive a short survey after they [4] _____ the service for one week. Please encourage them to report connection problems as well as useful features, since positive feedback alone will not identify the changes still needed.`,
    questions:[
      {choices:['submit','admit','commit','permit'],answer:'A',skills:['vocabulary','collocation'],difficulty:4,ruleId:'p6.fixed-phrase',explanation:'Submit the names means provide the requested list to Information Services.',explanationTh:'submit the names = ส่งรายชื่อให้ฝ่าย IT ทุกตัวเป็น verb จึงต้องตัดสินจากความหมายของการส่งข้อมูล',whyOthers:{B:'Admit refers to acknowledging something or allowing entry.',C:'Commit is not used to mean send a list of names.',D:'Permit means allow, not provide information.'}},
      {choices:['All devices will be replaced before the second trial begins.','The first trial did not involve any customer support employees.','For laptops, state both the model and the operating system currently installed.','Supervisors should wait until the survey arrives before sending the list.'],answer:'C',skills:['sentence-placement','context'],difficulty:5,ruleId:'p6.sentence-placement',explanation:'The sentence specifies the device information technicians need for preparing instructions; this in the next sentence refers to that information.',explanationTh:'ประโยคก่อนขอชนิด device ประโยคถัดไป This will allow technicians ... จึงต้องเติมรายละเอียดเครื่องที่ช่วยเตรียมคำแนะนำ',whyOthers:{A:'The email describes adjusted access, not replacing all devices.',B:'Customer support explicitly participated in the first phase.',D:'The list is needed before the trial, not after its survey.'}},
      {choices:['Unless','If','Even though','As if'],answer:'B',skills:['conjunction','context'],difficulty:4,ruleId:'p6.connector-context',explanation:'Reviewing other applications is conditional on satisfactory results from the trial.',explanationTh:'จะพิจารณาเพิ่ม applications เมื่อผลทดลองน่าพอใจ เป็นเงื่อนไขบวก ใช้ If ไม่ใช่ Unless',whyOthers:{A:'Unless reverses the condition and would mean reviewing expansion if results are unsatisfactory.',C:'Even though treats satisfactory results as a conceded fact, though they are not yet known.',D:'As if introduces an imagined comparison, not an eligibility condition.'}},
      {choices:['will use','using','were used','have used'],answer:'D',skills:['verb-tense'],difficulty:4,ruleId:'p6.verb-tense',explanation:'In this future time clause, have used expresses completion of one week of use before the survey arrives.',explanationTh:'หลัง after ที่พูดถึงเวลาอนาคตไม่ใช้ will ใช้ have used เน้นว่าทดลองครบหนึ่งสัปดาห์แล้วจึงรับแบบสำรวจ',whyOthers:{A:'Future time clauses introduced by after do not normally use will for this meaning.',B:'Using alone does not supply a finite verb.',C:'Were used makes the employees the objects being used.'}},
    ],
  },
  {
    id:'v9-p6-06',part:6,kind:'notice',title:'Equipment Returns After the Trade Exhibition',
    body:`NOTICE TO EXHIBITORS
Returning demonstration equipment

The exhibition hall will close to visitors at 5:00 P.M. on Sunday. Exhibitors may begin packing small display items immediately afterward, but large equipment must remain in place until the public corridors have been cleared. Hall supervisors will announce when loading carts may enter; please do not move them into the aisles in advance.

All rented screens and audio units must be returned to the equipment desk before 7:00 P.M. Staff will check each unit against the rental record and issue a signed receipt. Please keep this receipt until the deposit [1] _____ to your account. Refunds are normally processed within five business days, but incomplete returns can delay them.

Items belonging to the organizer should be returned [2] _____ of whether they were used during the exhibition. In particular, unused extension leads should not be left inside display cabinets, where they may be overlooked during the final inspection. [3] _____ Please compare the quantities on that list with the items you bring to the desk.

If your transport company cannot collect your own equipment on Sunday evening, contact the hall supervisor before noon. A secure storage area can be arranged for an additional charge. [4] _____, this option does not extend the deadline for returning rented equipment, which must still be handed in by 7:00 P.M.`,
    questions:[
      {choices:['have been returned','will return','has been returned','returning'],answer:'C',skills:['passive','verb-tense'],difficulty:4,ruleId:'p6.passive-tense',explanation:'The deposit receives the refund action, and until has been returned describes its completion.',explanationTh:'deposit เป็นเงินที่ถูกคืน ใช้ has been returned หลัง until เพื่อบอกว่าคืนเรียบร้อยแล้ว',whyOthers:{A:'Have been returned does not agree with the singular subject deposit.',B:'Will return is active and inappropriate in this time clause.',D:'Returning lacks a finite auxiliary and passive meaning.'}},
      {choices:['regardless','instead','capable','aware'],answer:'A',skills:['preposition','collocation'],difficulty:4,ruleId:'p6.fixed-phrase',explanation:'Regardless of whether they were used means used and unused items must both be returned.',explanationTh:'regardless of whether = ไม่ว่าจะใช้หรือไม่ได้ใช้ก็ต้องคืน อ่านต่อที่ย้ำ unused extension leads',whyOthers:{B:'Instead of would describe replacing one action with another.',C:'Capable of needs a subject describing ability.',D:'Aware of describes knowledge, not a universal return requirement.'}},
      {choices:['The signed receipt replaces the need to return unused accessories.','A list of all equipment issued to each booth was included with the rental confirmation.','The equipment desk will accept returns until the following Monday morning.','Any equipment found in a display cabinet automatically becomes the exhibitor’s property.'],answer:'B',skills:['sentence-placement','context'],difficulty:5,ruleId:'p6.sentence-placement',explanation:'That list in the next sentence requires an identifiable equipment list; this sentence introduces it without changing the return deadline.',explanationTh:'that list ในประโยคถัดไปต้องมี list ถูกกล่าวถึงก่อน จึงเลือก B ส่วนตัวลวงเปลี่ยนกฎการคืนของ',whyOthers:{A:'A receipt is issued after equipment is checked; it does not waive returns.',C:'The deadline is Sunday at 7:00 P.M.',D:'Organizer-owned equipment must be returned, even if unused.'}},
      {choices:['Therefore','Likewise','For example','However'],answer:'D',skills:['context','conjunction'],difficulty:4,ruleId:'p6.connector-context',explanation:'Storage is available for exhibitors’ own equipment, but it does not relax the rental-return deadline.',explanationTh:'มีบริการฝากของตัวเอง แต่ไม่ได้ยืด deadline ของเช่า เป็นข้อจำกัดของทางเลือกนี้ ใช้ However',whyOthers:{A:'An unchanged rental deadline is not the result of paying for storage.',B:'The sentence contrasts two policies rather than describing similar ones.',C:'It gives a limitation, not an example of a storage charge.'}},
    ],
  },
  {
    id:'v9-p7-01',part:7,kind:'article',title:'Brookfield Repair Centre Expands Its Booking System',
    body:`BROOKFIELD BUSINESS REVIEW — October 6

Brookfield Repair Centre will introduce an online booking system on November 1, following a six-week trial involving customers at its Lakeside branch. The company originally planned to introduce the system at all three branches simultaneously, but staff training at the Central branch has been delayed. That branch will continue taking bookings by telephone until December, while Lakeside and Riverside will offer both telephone and online bookings from November.

According to operations director Elena Park, the new system is intended to reduce the time employees spend calling customers to clarify repair requests. Customers will describe the problem and upload a photograph when making a booking. A technician will review those details before the appointment and contact the customer only if further information is required. The photograph is not a substitute for inspecting the item, and the final price will still be confirmed after inspection.

Customers who used the trial system were generally satisfied, although several assumed that selecting a time guaranteed that their repair would be completed that day. The revised confirmation message therefore states that the reserved time is for an assessment, not necessarily for the repair itself. Parts that are not held in stock may need to be ordered.

Park said the company would not offer discounted repairs merely to encourage online bookings. Instead, customers using the system will receive an automatic message when their item is ready for collection. Telephone customers will continue receiving a call from a member of staff. Both groups will remain eligible for the existing three-month workmanship guarantee.`,
    questions:[
      {stem:'Why will the Central branch introduce online bookings later than the other branches?',choices:['Its repair prices are still being reviewed.','Its employees have not completed the necessary training.','Customers there preferred automatic collection messages.','The Lakeside trial failed to attract enough users.'],answer:'B',skills:['detail','paraphrase'],difficulty:3,ruleId:'p7.detail',explanation:'The rollout is delayed specifically because staff training at Central has been delayed, not because the system failed.',explanationTh:'ต้องแยกเหตุเลื่อนเฉพาะ Central: staff training delayed ไม่ใช่ปัญหาจาก trial หรือราคา',evidence:'staff training at the Central branch has been delayed',whyOthers:{A:'The article describes inspection-based prices, not a price review delaying Central.',C:'Automatic messages are a benefit, not the reason for the delay.',D:'Trial customers were generally satisfied.'}},
      {stem:'What is the main purpose of uploading a photograph?',choices:['To establish the final repair price in advance.','To replace an inspection by a technician.','To help staff prepare for an assessment.','To qualify for the workmanship guarantee.'],answer:'C',skills:['purpose','paraphrase'],difficulty:4,ruleId:'p7.purpose',explanation:'Technicians review the problem details before the appointment; the photograph supports preparation but cannot replace inspection or fix the price.',explanationTh:'ภาพช่วย technician ดูข้อมูลก่อนนัด ลดการโทรถาม แต่ไม่แทน inspection และไม่ใช่การยืนยันราคา',evidence:'A technician will review those details before the appointment',whyOthers:{A:'The final price is confirmed after inspection.',B:'The text explicitly says the photograph is not a substitute for inspection.',D:'Both online and telephone customers receive the guarantee.'}},
      {stem:'What can be inferred about the confirmation message used during the trial?',choices:['It did not make the scope of the appointment sufficiently clear.','It required every customer to telephone the branch.', 'It promised discounted parts at all three branches.','It prevented customers from uploading photographs.'],answer:'A',skills:['inference'],difficulty:5,ruleId:'p7.inference',explanation:'Customers misunderstood an assessment booking as a promise of same-day repair, and the message was revised to clarify that distinction.',explanationTh:'trial มีคนเข้าใจผิดว่าจองแล้วซ่อมเสร็จวันเดียว จึงอนุมานว่าข้อความเดิมแยก assessment กับ repair ไม่ชัด',evidence:'The revised confirmation message therefore states that the reserved time is for an assessment',whyOthers:{B:'Customers used the online trial; no universal telephone requirement is stated.',C:'Discounts are explicitly not planned.',D:'Photographs are part of the booking process.'}},
      {stem:'Which benefit will be offered exclusively to online booking customers?',choices:['A reduced repair fee.','A three-month guarantee.','A telephone call when an item is ready.','An automatic collection notification.'],answer:'D',skills:['detail'],difficulty:4,ruleId:'p7.not-except',explanation:'Online users receive an automatic message; telephone users receive a staff call, while the guarantee applies to both groups.',explanationTh:'ต้องเทียบสิทธิ์ทั้งสองกลุ่ม: online ได้ automatic message เท่านั้น ส่วน guarantee ทั้งคู่ได้ ไม่มีส่วนลด',evidence:'customers using the system will receive an automatic message when their item is ready for collection',whyOthers:{A:'No discount is offered for booking online.',B:'Both groups receive the same guarantee.',C:'Telephone customers receive the staff call.'}},
    ],
  },
  {
    id:'v9-p7-02',part:7,kind:'multi',title:'Conference Room Reservation — Policy and Follow-up Email',
    body:`DOCUMENT 1 — MEETING FACILITY BOOKING POLICY

The Harbour Exchange offers three meeting rooms for external organizations. Room Aspen accommodates up to 18 participants and costs 2,400 baht for a half-day reservation. Room Birch accommodates up to 30 participants and costs 3,200 baht. Room Cedar accommodates up to 50 participants and costs 4,600 baht. These prices include a projector and drinking water. Catering must be ordered separately through our approved provider.

A half-day reservation covers either 8:30 A.M. to noon or 1:00 P.M. to 4:30 P.M. Access for setup is available 30 minutes before the reserved session. Organizations requesting earlier access must reserve the preceding half-day as well. A deposit equal to 25 percent of the room charge is required to secure the booking; the balance is due five business days before the event.

Room changes are permitted without an administrative fee if requested at least seven calendar days before the event, but the revised room charge will apply. Cancellation at least fourteen days before the event qualifies for a deposit refund. Later cancellations do not. Catering charges follow the provider's separate terms.

---

DOCUMENT 2 — EMAIL
From: Priya Sen, Maple Consulting
To: Harbour Exchange Reservations
Date: October 8
Subject: November 3 afternoon training

Thank you for confirming our reservation for Room Birch on November 3. We paid the deposit yesterday. Two of our client teams have now decided to attend remotely, reducing the number coming in person from 26 to 16. Please transfer our reservation to the smallest room that will accommodate everyone.

We will keep the afternoon session and do not need access before the usual setup time. Please let us know whether the difference between our original deposit and the deposit for the smaller room can be credited against the remaining balance. The caterer has already confirmed that our lunch order may be reduced without a charge, so we will contact them directly rather than include that change in your invoice.`,
    questions:[
      {stem:'Which room should Ms. Sen now be assigned?',choices:['Room Aspen','Room Birch','Room Cedar','Two adjoining rooms'],answer:'A',skills:['multi-text','detail'],difficulty:4,ruleId:'p7.multi-text',explanation:'The email reduces in-person attendance to 16; Aspen is the smallest room and holds 18.',explanationTh:'เชื่อม email จำนวนใหม่ 16 คนกับ policy: Aspen จุ18 และเป็นห้องเล็กสุดที่พอ ไม่ใช่เลือก Birch ตาม booking เดิม',evidence:'reducing the number coming in person from 26 to 16',whyOthers:{B:'Birch fits but is not the smallest suitable room.',C:'Cedar is much larger than required.',D:'One room already accommodates all 16 attendees.'}},
      {stem:'What is the difference between the original deposit and the deposit required for the new room?',choices:['200 baht','600 baht','800 baht','1,000 baht'],answer:'A',skills:['multi-text','inference'],difficulty:5,ruleId:'p7.multi-text',explanation:'Birch’s deposit is 25% of 3,200 = 800; Aspen’s is 25% of 2,400 = 600, a difference of 200 baht.',explanationTh:'อย่าสับสนค่าห้องกับมัดจำ: Birch800 − Aspen600 = 200 บาท ต่างจากราคาห้อง800บาท',evidence:'A deposit equal to 25 percent of the room charge is required',whyOthers:{B:'600 baht is the new deposit itself, not the difference.',C:'800 baht is the original deposit and also the difference in full room charges.',D:'1,000 baht is not obtained from either required deposit.'}},
      {stem:'At what time can Maple Consulting enter the room without reserving another session?',choices:['8:00 A.M.','Noon','12:30 P.M.','1:00 P.M.'],answer:'C',skills:['multi-text','detail'],difficulty:4,ruleId:'p7.multi-text',explanation:'The afternoon session starts at 1:00 P.M., and setup access begins 30 minutes earlier.',explanationTh:'email ยังคง afternoon session; policy ให้ setup ก่อน30นาที จึงเข้า12:30 ไม่ต้องจองช่วงเช้า',evidence:'Access for setup is available 30 minutes before the reserved session.',whyOthers:{A:'8:00 is setup time for a morning reservation.',B:'Noon is earlier than the included setup allowance.',D:'1:00 is the session start, not the earliest included access.'}},
      {stem:'What is indicated about Ms. Sen’s requested changes?',choices:['The facility must refund the entire deposit.','The room transfer is early enough to avoid an administrative fee.','The facility will revise the catering order on her behalf.','The event must be moved to a different date.'],answer:'B',skills:['multi-text','inference'],difficulty:5,ruleId:'p7.inference',explanation:'October 8 is more than seven days before November 3, so the room change can avoid the administrative fee; a deposit credit is only requested, not confirmed.',explanationTh:'เทียบวันที่ Oct8 กับ Nov3 เกิน7วัน จึงไม่เสีย administrative fee แต่ยังสรุปไม่ได้ว่าจะ refund/credit มัดจำ เพราะเธอเพียงขอ',evidence:'Room changes are permitted without an administrative fee if requested at least seven calendar days before the event',whyOthers:{A:'She asks about crediting a difference; no full refund is confirmed.',C:'She will contact the caterer directly.',D:'She explicitly keeps the same date and afternoon session.'}},
    ],
  },
  {
    id:'v9-p7-03',part:7,kind:'multi',title:'Replacement Order — Delivery Policy, Invoice and Customer Chat',
    body:`DOCUMENT 1 — NORTHLINE OFFICE SUPPLIES: DELIVERY AND RETURNS

Standard delivery is free on orders of at least 5,000 baht after all discounts have been applied. Smaller orders incur a 180-baht delivery charge. Orders confirmed before 2:00 P.M. on a business day are normally dispatched that afternoon; later orders are dispatched the next business day. Delivery usually takes two business days after dispatch. Saturdays, Sundays and public holidays are not business days.

If goods arrive damaged, customers should send photographs and the invoice number within three business days of delivery. We can then arrange replacement of the affected items at no additional delivery cost. A refund is available instead, but the damaged goods must be returned. Original delivery charges are not refunded unless the entire shipment was delivered to the wrong address. For replacement deliveries, customers may specify another address before dispatch. Changes after dispatch cannot be guaranteed.

---

DOCUMENT 2 — INVOICE NL-4821
Customer: Arden Architecture
Order confirmed: Monday, October 5, 1:40 P.M.
24 desk lamps at 220 baht: 5,280 baht
Corporate discount, 10 percent: minus 528 baht
Goods total after discount: 4,752 baht
Standard delivery: 180 baht
Invoice total: 4,932 baht
Delivery address: Arden Architecture, 18 Willow Road
Delivered: Wednesday, October 7, 10:15 A.M.

---

DOCUMENT 3 — CUSTOMER SERVICE CHAT, THURSDAY OCTOBER 8
9:05 — Leo, Arden Architecture: Five lamps arrived with cracked bases. The other nineteen are working. I have emailed photographs and invoice NL-4821. We would prefer replacements rather than a refund.
9:08 — Maya, Northline: Thank you. Your report is within the required period. The replacement stock will reach our warehouse tomorrow morning, and we can send the five lamps that afternoon. You may keep the damaged lamps until we advise you about collection.
9:11 — Leo: Our Willow Road office will be closed next week. Please send the replacements to our temporary studio at 46 Elm Street. Is there time to change the address?
9:13 — Maya: Yes, the replacement order has not left the warehouse. I have updated the address. There will be no new delivery charge, but the delivery charge on the original invoice remains payable.
9:15 — Leo: Understood. Please email the dispatch confirmation so our studio receptionist knows which shipment to expect.`,
    questions:[
      {stem:'Why was Arden Architecture charged for delivery on the original order?',choices:['It requested delivery to a temporary address.','Its order was confirmed after the daily cutoff.','Its discounted goods total was below the free-delivery threshold.','It ordered fewer than twenty-five lamps.'],answer:'C',skills:['multi-text','detail'],difficulty:4,ruleId:'p7.multi-text',explanation:'The policy uses the total after discounts; 4,752 is below 5,000 even though the original goods subtotal is 5,280.',explanationTh:'ต้องดู after all discounts: 4,752 < 5,000 จึงเสีย180 ไม่ใช่ใช้ยอดก่อนลด5,280',evidence:'Standard delivery is free on orders of at least 5,000 baht after all discounts have been applied.',whyOthers:{A:'The address change applies only to the later replacement order.',B:'The original order was confirmed at 1:40, before 2:00.',D:'The policy uses order value, not a minimum number of lamps.'}},
      {stem:'When will the replacements most likely arrive, assuming the normal delivery time?',choices:['Friday, October 9','Saturday, October 10','Monday, October 12','Tuesday, October 13'],answer:'D',skills:['multi-text','inference'],difficulty:5,ruleId:'p7.multi-text',explanation:'The Thursday chat promises Friday dispatch; two business days after Friday are Monday and Tuesday.',explanationTh:'แชตวันThu8 บอกส่งtomorrow=Fri9 แล้วนับ2 business days หลังdispatch: Mon12วันแรก Tue13วันที่สอง ต้องข้ามสุดสัปดาห์',evidence:'Delivery usually takes two business days after dispatch.',whyOthers:{A:'Friday is the expected dispatch date, not the delivery date.',B:'Saturday is excluded from business days.',C:'Monday is only the first business day after Friday dispatch.'}},
      {stem:'What made the change to the replacement delivery address possible?',choices:['The replacement shipment had not been dispatched.','Arden had returned all twenty-four lamps.','The original invoice had been canceled.','Elm Street was closer to the supplier’s warehouse.'],answer:'A',skills:['multi-text','paraphrase'],difficulty:4,ruleId:'p7.paraphrase',explanation:'The policy permits an address change before dispatch, and Maya confirms that the replacement order has not left the warehouse.',explanationTh:'policy อนุญาตก่อนdispatch และแชตยืนยัน not left the warehouse ต้องเชื่อมสองเอกสาร',evidence:'the replacement order has not left the warehouse',whyOthers:{B:'Arden keeps nineteen working lamps and has not returned the damaged ones.',C:'The original delivery charge remains payable.',D:'No comparison of distance is given.'}},
      {stem:'Which statement is NOT supported by the documents?',choices:['The report of damage was made within the required period.','Arden will receive replacements for five lamps.','The original delivery charge will be removed from the invoice.','The replacements will go to the temporary studio.'],answer:'C',skills:['multi-text','detail'],difficulty:5,ruleId:'p7.not-except',explanation:'Maya explicitly says the original delivery charge remains payable; no additional charge for replacement shipping is a different benefit.',explanationTh:'ตัวลวงคือ free replacement shipping ≠ refund original delivery fee แชตบอกของเดิมยังต้องจ่าย180',evidence:'the delivery charge on the original invoice remains payable',whyOthers:{A:'Maya explicitly confirms the report is within the period.',B:'She confirms that five replacement lamps can be sent.',D:'She says the address has been updated.'}},
      {stem:'In the chat, what does Leo most likely mean by “Understood”?',choices:['He agrees to collect the replacement stock himself.','He accepts that the original delivery fee is still due.','He withdraws the request to change the address.','He now prefers a refund instead of replacements.'],answer:'B',skills:['inference','context'],difficulty:4,ruleId:'p7.inference',explanation:'The response immediately follows the clarification that only the new delivery is free, and Leo proceeds to request a dispatch email.',explanationTh:'ดูข้อความก่อนหน้า Maya ย้ำค่าจัดส่งเดิมยัง payable; Understood คือรับทราบเงื่อนไขนี้ แล้วขอemailเพื่อรอของต่อ',evidence:'There will be no new delivery charge, but the delivery charge on the original invoice remains payable.',whyOthers:{A:'He requests a delivery confirmation for the studio receptionist.',C:'The studio address change is already confirmed.',D:'He continues discussing the replacement shipment.'}},
    ],
  },
  {
    id:'v9-p7-04',part:7,kind:'notice',title:'Northbridge Shared Workspace — New Membership Rules',
    body:`MEMBER UPDATE — EFFECTIVE NOVEMBER 1

Northbridge Shared Workspace is changing the way meeting rooms are included in monthly memberships. Existing members will retain their current allowance until their next renewal date. New memberships purchased on or after November 1 will include eight hours of meeting-room use each month. Additional hours may be purchased in advance at the published member rate. Unused included hours cannot be carried into the following month or transferred to another member.

The booking calendar will now display both reserved and provisional sessions. A provisional booking holds a room for twenty minutes while a member completes payment for any additional hours. If payment is not completed within that period, the room will be released automatically. Members using only their included hours will receive immediate confirmation and will not need to enter payment details.

Bookings may be canceled without using any of the member's allowance until two hours before the reserved start time. Later cancellations will use the full number of hours booked, even if another member subsequently reserves the room. A cancellation caused by a building-wide power failure will be handled differently: the booked hours will be restored, and any payment for additional hours will be refunded.

Members who share a room with guests remain responsible for the booking. Guests do not need a membership, but their names must be entered at least one hour before arrival so reception can prepare visitor passes. Please do not send guests directly to the meeting floor before they have collected those passes. Questions about renewals should be directed to Member Services; technical problems with the booking calendar should be reported through the support form.`,
    questions:[
      {stem:'When will an existing member become subject to the new allowance?',choices:['On November 1 in every case.','When the booking calendar is next updated.','At the member’s next renewal.','After the member uses eight meeting-room hours.'],answer:'C',skills:['detail','paraphrase'],difficulty:4,ruleId:'p7.detail',explanation:'Existing members retain their old allowance until their next renewal, whereas new memberships from November 1 use the new allowance immediately.',explanationTh:'ต้องแยก existing กับ new: สมาชิกเดิมใช้สิทธิ์เดิมจนrenewal ไม่ใช่เปลี่ยนNov1ทุกคน',evidence:'Existing members will retain their current allowance until their next renewal date.',whyOthers:{A:'November 1 applies immediately to new memberships, not all existing ones.',B:'No calendar-update trigger is stated.',D:'The trigger is renewal, not reaching eight hours of use.'}},
      {stem:'What will happen if a member fails to pay for extra hours within twenty minutes?',choices:['The provisional room reservation will expire.','The member’s monthly allowance will increase.','The booking will become free of charge.','Reception will contact the guests for payment.'],answer:'A',skills:['detail','paraphrase'],difficulty:3,ruleId:'p7.paraphrase',explanation:'An unpaid provisional booking is released automatically after the twenty-minute payment period.',explanationTh:'provisionalคือถือห้องชั่วคราว จ่ายไม่ทัน20นาทีระบบปล่อยห้อง ไม่ใช่กลายเป็นconfirmed/free',evidence:'the room will be released automatically',whyOthers:{B:'Unpaid extra hours do not increase included hours.',C:'The room is released rather than made free.',D:'The member remains responsible; guests are not billed.'}},
      {stem:'Which situation allows booked hours to be restored after a cancellation made less than two hours before the session?',choices:['Another member books the same room.','A guest cannot arrive on time.','The member submits a technical support form.','A power failure affects the whole building.'],answer:'D',skills:['detail','inference'],difficulty:5,ruleId:'p7.not-except',explanation:'The building-wide power failure is the explicit exception to the late-cancellation charge; another member rebooking does not restore hours.',explanationTh:'ต้องจับข้อยกเว้นเฉพาะ building-wide power failure คืนชั่วโมงและเงิน ส่วนคนอื่นจองแทนยังถูกหักชั่วโมง',evidence:'A cancellation caused by a building-wide power failure will be handled differently',whyOthers:{A:'The policy explicitly charges late cancellations even if another member rebooks.',B:'A guest’s delay is not an exception.',C:'Reporting a technical problem alone does not trigger restoration.'}},
    ],
  },
]

export const extraPassagesV9: Passage[] = seeds.map(seed => ({
  id:seed.id,part:seed.part,kind:seed.kind,title:seed.title,body:seed.body,examStyle:true,
  questions:seed.questions.map((_, index) => `${seed.id}-q${index + 1}`),
  sourceLabel:'Original TOEIC-style practice informed by ETS sample formats; not official ETS questions.',
}))

export const extraReadingV9: Question[] = seeds.flatMap(seed => seed.questions.map((item, index) => ({
  ...item,id:`${seed.id}-q${index + 1}`,part:seed.part,passageId:seed.id,
  stem:item.stem ?? `[${index + 1}] _____`,
  choices:item.choices.map((text, choiceIndex) => ({id:['A','B','C','D'][choiceIndex],text})),
  targetSeconds:seed.part === 6 ? item.skills.includes('sentence-placement') ? 60 : 45 : item.difficulty === 5 ? 100 : 80,
})))
