import type { Question } from './types'

const c = (a:string,b:string,c:string,d:string) => [
  {id:'A',text:a},{id:'B',text:b},{id:'C',text:c},{id:'D',text:d},
]

export const vocabRepairQuestions:Question[] = [
  {
    id:'vocab-repair-subject-to',part:5,
    stem:'The dates printed in the preliminary schedule are _____ to change before registration opens.',
    choices:c('subject','estate','esteem','contain'),answer:'A',
    skills:['vocabulary','collocation'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[21,26],
    explanation:'“Be subject to change” is a fixed expression meaning that something may be changed later.',
    explanationTh:'วลีตายตัว be subject to change = อาจมีการเปลี่ยนแปลงภายหลัง คำว่า subject ในที่นี้ไม่ได้แปลว่า “วิชา/ประธาน”',
    translationTh:'วันที่ในตารางเบื้องต้นอาจมีการเปลี่ยนแปลงก่อนเปิดลงทะเบียน',
    choiceTranslationsTh:{A:'subject to = อยู่ภายใต้/อาจมีการ...',B:'estate = ทรัพย์สิน/ที่ดิน/กองมรดก',C:'esteem = ยกย่อง/เคารพ',D:'contain = บรรจุ/ประกอบด้วย'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-inconvenience',part:5,
    stem:'The theater apologized for any _____ caused by the temporary closure of its main entrance.',
    choices:c('inconvenience','inconsistency','inexperience','independence'),answer:'A',
    skills:['vocabulary','collocation'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[21,26],
    explanation:'“Cause inconvenience” is the natural expression for creating difficulty or trouble for someone.',
    explanationTh:'cause inconvenience = ทำให้เกิดความไม่สะดวก เป็น collocation ที่ใช้ในประกาศ/อีเมลธุรกิจบ่อย',
    translationTh:'โรงละครขออภัยในความไม่สะดวกที่เกิดจากการปิดทางเข้าหลักชั่วคราว',
    choiceTranslationsTh:{A:'inconvenience = ความไม่สะดวก',B:'inconsistency = ความไม่สอดคล้องกัน',C:'inexperience = การขาดประสบการณ์',D:'independence = ความเป็นอิสระ'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-conduct',part:5,
    stem:'The research institute will _____ a follow-up survey after the pilot program ends.',
    choices:c('conduct','construct','contain','contact'),answer:'A',
    skills:['vocabulary','collocation'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[21,26],
    explanation:'The natural collocation is “conduct a survey,” meaning carry out a survey.',
    explanationTh:'conduct a survey = ดำเนินการสำรวจ ส่วน construct = ก่อสร้าง, contain = บรรจุ/ประกอบด้วย, contact = ติดต่อ',
    translationTh:'สถาบันวิจัยจะดำเนินการสำรวจติดตามผลหลังโครงการทดลองสิ้นสุด',
    choiceTranslationsTh:{A:'conduct = ดำเนินการ',B:'construct = ก่อสร้าง/สร้าง',C:'contain = บรรจุ/ประกอบด้วย',D:'contact = ติดต่อ'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-prompt',part:5,
    stem:'Guests appreciated the hotel staff’s _____ response to the unexpected power outage.',
    choices:c('prompt','promptly','promptness','prompting'),answer:'A',
    skills:['vocabulary','part-of-speech'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[3,21],
    explanation:'The noun “response” needs an adjective. “Prompt” means quick or without unnecessary delay.',
    explanationTh:'response เป็นคำนาม จึงต้องใช้ adjective ขยาย: prompt response = การตอบสนองที่รวดเร็ว',
    translationTh:'แขกชื่นชมการตอบสนองอย่างรวดเร็วของพนักงานโรงแรมต่อเหตุไฟดับที่ไม่คาดคิด',
    choiceTranslationsTh:{A:'prompt = รวดเร็ว/ทันที (Adj.)',B:'promptly = อย่างรวดเร็ว (Adv.)',C:'promptness = ความรวดเร็ว (N.)',D:'prompting = การกระตุ้น/การเตือน'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-satisfaction',part:5,
    stem:'The questionnaire asks customers to rate their _____ with the installation service.',
    choices:c('satisfy','satisfied','satisfaction','satisfactorily'),answer:'C',
    skills:['vocabulary','part-of-speech'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[2,21],
    explanation:'After possessive “their,” the sentence needs a noun. “Satisfaction with” is the natural phrase.',
    explanationTh:'หลัง their ต้องเป็น noun และวลีคือ satisfaction with = ความพึงพอใจกับ...',
    translationTh:'แบบสอบถามให้ลูกค้าประเมินความพึงพอใจต่อบริการติดตั้ง',
    choiceTranslationsTh:{A:'satisfy = ทำให้พอใจ (V.)',B:'satisfied = รู้สึกพอใจ (Adj.)',C:'satisfaction = ความพึงพอใจ (N.)',D:'satisfactorily = อย่างน่าพอใจ (Adv.)'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-care',part:5,
    stem:'Museum employees must handle the borrowed artifacts with great _____.',
    choices:c('careful','carefully','care','caring'),answer:'C',
    skills:['vocabulary','collocation','part-of-speech'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[1,21],
    explanation:'The fixed phrase is “with great care.” After the adjective “great,” a noun is required.',
    explanationTh:'วลีคือ with great care = ด้วยความระมัดระวัง โดย great เป็น adjective จึงต้องตามด้วย noun “care”',
    translationTh:'พนักงานพิพิธภัณฑ์ต้องจัดการวัตถุที่ยืมมาด้วยความระมัดระวังอย่างมาก',
    choiceTranslationsTh:{A:'careful = ระมัดระวัง (Adj.)',B:'carefully = อย่างระมัดระวัง (Adv.)',C:'care = ความระมัดระวัง/การดูแล (N.)',D:'caring = เอาใจใส่/การดูแล'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-realistic',part:5,
    stem:'After the supplier confirmed its capacity, the revised production target appeared more _____ .',
    choices:c('realism','realistic','realistically','realize'),answer:'B',
    skills:['vocabulary','part-of-speech','comparison'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[3,18,21],
    explanation:'After the linking verb “appeared” and “more,” an adjective describing the target is required: realistic.',
    explanationTh:'appeared เป็น linking verb และมี more หน้า blank จึงต้อง adjective: more realistic = สมเหตุสมผล/เป็นไปได้จริงมากขึ้น',
    translationTh:'หลังผู้จัดส่งยืนยันกำลังการผลิต เป้าหมายการผลิตที่แก้ไขแล้วก็ดูเป็นไปได้จริงมากขึ้น',
    choiceTranslationsTh:{A:'realism = ความสมจริง (N.)',B:'realistic = สมจริง/เป็นไปได้จริง (Adj.)',C:'realistically = อย่างสมจริง (Adv.)',D:'realize = ตระหนัก/ทำให้เป็นจริง (V.)'},
    targetSeconds:30,
  },
  {
    id:'vocab-repair-strictly',part:5,
    stem:'Access to the archive is _____ controlled because it contains confidential records.',
    choices:c('strict','strictly','strictness','stricter'),answer:'B',
    skills:['vocabulary','part-of-speech'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[5,21],
    explanation:'The blank modifies “controlled,” so an adverb is required: strictly controlled.',
    explanationTh:'controlled เป็นคำที่ถูกขยาย จึงใช้ adverb “strictly” = อย่างเคร่งครัด',
    translationTh:'การเข้าถึงคลังเอกสารถูกควบคุมอย่างเคร่งครัดเพราะมีข้อมูลลับ',
    choiceTranslationsTh:{A:'strict = เข้มงวด (Adj.)',B:'strictly = อย่างเคร่งครัด (Adv.)',C:'strictness = ความเข้มงวด (N.)',D:'stricter = เข้มงวดกว่า (comparative Adj.)'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-appealing',part:5,
    stem:'The designer made the new registration page more visually _____ without changing its layout.',
    choices:c('appeal','appealing','appealingly','appealed'),answer:'B',
    skills:['vocabulary','part-of-speech'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[3,5,21],
    explanation:'“Visually” is an adverb modifying the adjective “appealing.” The page is visually appealing.',
    explanationTh:'visually เป็น adverb จึงไปขยาย adjective “appealing” → visually appealing = ดูน่าดึงดูด',
    translationTh:'นักออกแบบทำให้หน้าลงทะเบียนใหม่ดูน่าดึงดูดยิ่งขึ้นโดยไม่เปลี่ยนเลย์เอาต์',
    choiceTranslationsTh:{A:'appeal = ดึงดูด/การอุทธรณ์ (V./N.)',B:'appealing = น่าดึงดูด (Adj.)',C:'appealingly = อย่างน่าดึงดูด (Adv.)',D:'appealed = ดึงดูด/อุทธรณ์แล้ว (V2/V3)'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-estimate',part:5,
    stem:'Before approving the event, the committee asked Finance to _____ the total transportation cost.',
    choices:c('estimate','esteem','establishing','estate'),answer:'A',
    skills:['vocabulary','collocation'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[17,21,26],
    explanation:'After “to,” a base verb is needed. “Estimate the cost” means calculate an approximate amount.',
    explanationTh:'หลัง to ต้องเป็น V1 และ estimate the cost = ประมาณการค่าใช้จ่าย จึงถูกทั้ง Grammar และความหมาย',
    translationTh:'ก่อนอนุมัติงาน คณะกรรมการขอให้ฝ่ายการเงินประมาณการค่าเดินทางทั้งหมด',
    choiceTranslationsTh:{A:'estimate = ประมาณ/ประเมิน',B:'esteem = ยกย่อง/เคารพ',C:'establishing = การกำลังก่อตั้ง (V-ing)',D:'estate = ทรัพย์สิน/ที่ดิน/กองมรดก (N.)'},
    targetSeconds:30,
  },
  {
    id:'vocab-repair-recall',part:5,
    stem:'The manufacturer announced a nationwide product _____ after tests revealed a battery defect.',
    choices:c('recall','receipt','retreat','returning'),answer:'A',
    skills:['vocabulary','collocation'],difficulty:3,ruleId:'vocab.personal-repair',chapterIds:[21,26],
    explanation:'“Product recall” is the standard term for asking customers to return a defective or unsafe product.',
    explanationTh:'product recall = การเรียกคืนสินค้าเมื่อพบปัญหาหรือความไม่ปลอดภัย',
    translationTh:'ผู้ผลิตประกาศเรียกคืนสินค้าทั่วประเทศหลังการทดสอบพบข้อบกพร่องของแบตเตอรี่',
    choiceTranslationsTh:{A:'recall = การเรียกคืนสินค้า',B:'receipt = ใบเสร็จ',C:'retreat = การถอย/ล่าถอย',D:'returning = การกลับ/การส่งคืน (V-ing)'},
    targetSeconds:28,
  },
  {
    id:'vocab-repair-streamline',part:5,
    stem:'The digital signature feature is intended to _____ the contract approval process.',
    choices:c('streamline','stream','straighten up','strength'),answer:'A',
    skills:['vocabulary','collocation'],difficulty:4,ruleId:'vocab.personal-repair',chapterIds:[21,26],
    explanation:'“Streamline a process” means make it simpler, faster, and more efficient.',
    explanationTh:'streamline a process = ทำกระบวนการให้กระชับ ง่าย และมีประสิทธิภาพขึ้น',
    translationTh:'ฟีเจอร์ลายเซ็นดิจิทัลมีไว้เพื่อทำให้กระบวนการอนุมัติสัญญากระชับและมีประสิทธิภาพขึ้น',
    choiceTranslationsTh:{A:'streamline = ทำให้กระชับ/มีประสิทธิภาพขึ้น',B:'stream = กระแส/สตรีมข้อมูล',C:'straighten up = จัดให้ตรง/เป็นระเบียบ',D:'strength = ความแข็งแรง/จุดแข็ง (N.)'},
    targetSeconds:30,
  },
]
