import type { Question, SkillId } from './types'

const c = (a: string, b: string, c: string, d: string) => [
  { id: 'A', text: a }, { id: 'B', text: b }, { id: 'C', text: c }, { id: 'D', text: d },
]

type Item = [string, [string, string, string, string], string]
type RuleSet = {
  id: string
  skills: SkillId[]
  chapterIds: number[]
  difficulty: 1 | 2 | 3 | 4 | 5
  explanation: string
  items: Item[]
}

const rules: RuleSet[] = [
  {
    id:'wordform.adjective-before-noun', skills:['part-of-speech'], chapterIds:[3,6], difficulty:2,
    explanation:'The blank comes directly before a noun, so an adjective is required.',
    items:[
      ['The committee requested a _____ explanation of the revised budget.', ['clarity','clear','clearly','clarify'], 'B'],
      ['The supplier offered a _____ solution to the packaging problem.', ['practice','practical','practically','practicing'], 'B'],
      ['The hotel introduced a more _____ check-in procedure.', ['efficiency','efficient','efficiently','efficientize'], 'B'],
      ['The board expects a _____ improvement in quarterly revenue.', ['significance','significant','significantly','signify'], 'B'],
      ['The technician provided a _____ estimate of the repair time.', ['reliability','reliable','reliably','rely'], 'B'],
      ['The company needs a _____ strategy for reducing delivery delays.', ['flexibility','flexible','flexibly','flex'], 'B'],
      ['The audit found several _____ errors in the expense records.', ['notice','noticeable','noticeably','noticing'], 'B'],
      ['The seminar offers _____ guidance for first-time managers.', ['use','useful','usefully','usefulness'], 'B'],
    ],
  },
  {
    id:'wordform.adverb-modifier', skills:['part-of-speech'], chapterIds:[5,6], difficulty:2,
    explanation:'The blank modifies a verb, adjective, or another adverb, so an adverb is required.',
    items:[
      ['The staff responded _____ to the customer complaint.', ['professional','professionally','profession','professionalism'], 'B'],
      ['The new software runs _____ on older computers.', ['smooth','smoothly','smoothness','smoothing'], 'B'],
      ['The warehouse was _____ damaged during the storm.', ['serious','seriously','seriousness','seriousnesses'], 'B'],
      ['Ms. Kim explained the policy _____ during orientation.', ['clear','clearly','clarity','clarify'], 'B'],
      ['The figures were _____ different from the original forecast.', ['substantial','substantially','substance','substantiate'], 'B'],
      ['The team completed the migration _____ ahead of schedule.', ['success','successful','successfully','succeed'], 'C'],
      ['The revised form can be submitted _____ online.', ['easy','easily','ease','easier'], 'B'],
      ['The equipment is inspected _____ before each use.', ['thorough','thoroughly','thoroughness','thoroughing'], 'B'],
    ],
  },
  {
    id:'wordform.noun-position', skills:['part-of-speech'], chapterIds:[1,2,6], difficulty:2,
    explanation:'The grammar around the blank requires a noun, such as after an article, possessive, or as a verb object.',
    items:[
      ['The manager expressed her _____ with the final design.', ['satisfy','satisfied','satisfaction','satisfactorily'], 'C'],
      ['A full _____ of the safety system will take place tomorrow.', ['inspect','inspection','inspective','inspecting'], 'B'],
      ['The new policy has improved employee _____.', ['productive','productivity','productively','produce'], 'B'],
      ['Please provide written _____ of your reservation.', ['confirm','confirmation','confirmed','confirming'], 'B'],
      ['The survey measured customer _____ with the support team.', ['satisfy','satisfaction','satisfactory','satisfactorily'], 'B'],
      ['The proposal includes a detailed _____ of projected costs.', ['analyze','analysis','analytical','analytically'], 'B'],
      ['Management approved the _____ of two additional technicians.', ['hire','hiring','hired','hires'], 'B'],
      ['The system sends a _____ when a payment is processed.', ['notify','notification','notified','notifying'], 'B'],
    ],
  },
  {
    id:'tense.present-perfect-since', skills:['verb-tense'], chapterIds:[11], difficulty:2,
    explanation:'Since marks a starting point in the past that is connected to the present, so the present perfect is required.',
    items:[
      ['The company _____ three new branches since January.', ['opens','opened','has opened','is opening'], 'C'],
      ['Ms. Rao _____ the regional office since 2023.', ['manages','managed','has managed','is managing'], 'C'],
      ['Online sales _____ steadily since the website was redesigned.', ['increase','increased','have increased','are increasing'], 'C'],
      ['The support team _____ more than 500 requests since Monday.', ['handles','handled','has handled','is handling'], 'C'],
      ['Several procedures _____ since the new director arrived.', ['change','changed','have changed','are changing'], 'C'],
      ['The hotel _____ free airport transfers since last summer.', ['offers','offered','has offered','is offering'], 'C'],
      ['The laboratory _____ the same supplier since it opened.', ['uses','used','has used','is using'], 'C'],
      ['Customer satisfaction _____ significantly since the training program began.', ['improves','improved','has improved','is improving'], 'C'],
    ],
  },
  {
    id:'tense.past-perfect-sequence', skills:['verb-tense'], chapterIds:[11], difficulty:3,
    explanation:'When one past action was completed before another past action, the earlier action is expressed with the past perfect.',
    items:[
      ['By the time the client arrived, the staff _____ the meeting room.', ['prepares','had prepared','has prepared','is preparing'], 'B'],
      ['The shipment _____ before the warehouse closed for the holiday.', ['left','had left','has left','leaves'], 'B'],
      ['Ms. Gomez discovered that the invoice _____ twice.', ['was paid','had been paid','has paid','pays'], 'B'],
      ['Before the inspection began, the technicians _____ all safety checks.', ['complete','had completed','have completed','are completing'], 'B'],
      ['The guests were seated after the staff _____ the final table settings.', ['arranged','had arranged','has arranged','arranges'], 'B'],
      ['The manager realized that she _____ the wrong attachment.', ['sent','had sent','has sent','sends'], 'B'],
      ['Production resumed after the damaged valve _____ replaced.', ['was','had been','has been','is being'], 'B'],
      ['When the auditor called, the finance team already _____ the records.', ['reviews','had reviewed','has reviewed','is reviewing'], 'B'],
    ],
  },
  {
    id:'tense.future-progressive', skills:['verb-tense'], chapterIds:[11], difficulty:3,
    explanation:'The time expression points to a future action or an action that will be in progress at a specific future time.',
    items:[
      ['The company _____ its new product line next month.', ['launches','launched','will launch','has launched'], 'C'],
      ['At this time tomorrow, the team _____ the final presentation.', ['gives','gave','will be giving','has given'], 'C'],
      ['The new branch _____ operations on November 1.', ['began','will begin','has begun','beginning'], 'B'],
      ['By next Friday, the contractor _____ the lobby renovation.', ['will complete','will have completed','completed','completes'], 'B'],
      ['The audit team _____ in Bangkok throughout next week.', ['works','worked','will be working','has worked'], 'C'],
      ['The supplier _____ the replacement units by the end of the month.', ['delivered','will have delivered','delivers','has delivering'], 'B'],
      ['We _____ the updated schedule as soon as it is approved.', ['send','sent','will send','have sent'], 'C'],
      ['At 3:00 P.M. tomorrow, Ms. Chen _____ with the overseas distributor.', ['meets','met','will be meeting','has met'], 'C'],
    ],
  },
  {
    id:'sva.head-subject', skills:['subject-verb'], chapterIds:[10], difficulty:3,
    explanation:'Find the true head subject and ignore nouns inside prepositional phrases or other modifiers.',
    items:[
      ['The quality of the replacement parts _____ acceptable.', ['are','is','have','be'], 'B'],
      ['A list of approved vendors _____ available online.', ['are','is','have','were'], 'B'],
      ['The results of the recent survey _____ encouraging.', ['is','are','has','was'], 'B'],
      ['The cost of the repairs _____ higher than expected.', ['are','is','have','were'], 'B'],
      ['One of the conference speakers _____ written a book on logistics.', ['have','has','are','were'], 'B'],
      ['Each of the new employees _____ a security badge.', ['receive','receives','receiving','have'], 'B'],
      ['The number of online orders _____ increased this quarter.', ['have','has','are','were'], 'B'],
      ['A series of training sessions _____ scheduled for November.', ['are','is','have','were'], 'B'],
    ],
  },
  {
    id:'sva.correlative', skills:['subject-verb','conjunction'], chapterIds:[10,19], difficulty:4,
    explanation:'With either...or and neither...nor, the verb normally agrees with the nearer subject.',
    items:[
      ['Neither the supervisor nor the technicians _____ available today.', ['is','are','was','be'], 'B'],
      ['Either the assistants or the manager _____ the final report.', ['prepare','prepares','preparing','have prepared'], 'B'],
      ['Neither the printers nor the copier _____ working properly.', ['are','is','have','be'], 'B'],
      ['Either the director or the department heads _____ the announcement.', ['makes','make','making','has made'], 'B'],
      ['Neither the sales manager nor the representatives _____ received the revised price list.', ['has','have','is','was'], 'B'],
      ['Either the conference room or the two smaller offices _____ suitable.', ['is','are','has','be'], 'B'],
      ['Neither the accountant nor the auditors _____ identified the discrepancy.', ['has','have','is','was'], 'B'],
      ['Either the technicians or the supervisor _____ responsible for the final inspection.', ['are','is','have','be'], 'B'],
    ],
  },
  {
    id:'passive.core', skills:['passive','verb-tense'], chapterIds:[14], difficulty:3,
    explanation:'The subject receives the action, so use the appropriate passive form: BE + past participle.',
    items:[
      ['All applications must _____ before Friday.', ['review','be reviewed','reviewed','be reviewing'], 'B'],
      ['The final schedule _____ to participants yesterday.', ['sent','was sent','has sent','is sending'], 'B'],
      ['The equipment has _____ regularly since installation.', ['inspect','been inspected','inspecting','been inspect'], 'B'],
      ['Several employees will _____ to the new office next month.', ['transfer','be transferred','transferred','be transferring'], 'B'],
      ['The conference room is being _____ for the afternoon workshop.', ['prepare','prepared','preparing','prepares'], 'B'],
      ['The damaged products should _____ immediately.', ['replace','be replaced','replaced','be replacing'], 'B'],
      ['The invoices have not _____ yet.', ['approve','been approved','approving','been approve'], 'B'],
      ['The new branch is expected _____ by March.', ['complete','to be completed','to complete','completing'], 'B'],
    ],
  },
  {
    id:'gerund.after-preposition', skills:['verb-tense','preposition'], chapterIds:[17], difficulty:3,
    explanation:'A verb that follows a preposition is normally in the gerund (-ing) form.',
    items:[
      ['The team succeeded in _____ the installation ahead of schedule.', ['complete','completing','completed','completion'], 'B'],
      ['Ms. Park is responsible for _____ the workshop.', ['coordinate','coordinating','coordinated','coordination'], 'B'],
      ['Employees are interested in _____ more about the new benefits.', ['learn','learning','learned','to learned'], 'B'],
      ['We look forward to _____ you at the conference.', ['meet','meeting','met','to meet'], 'B'],
      ['The company is considering _____ its customer service hours.', ['extend','extending','extended','to extending'], 'B'],
      ['The manager apologized for _____ the meeting on short notice.', ['cancel','canceling','canceled','to cancel'], 'B'],
      ['The technician finished _____ the software before noon.', ['install','installing','installed','to installing'], 'B'],
      ['Staff members are used to _____ with overseas clients.', ['work','working','worked','to work'], 'B'],
    ],
  },
  {
    id:'infinitive.pattern', skills:['verb-tense'], chapterIds:[17], difficulty:2,
    explanation:'The governing verb or phrase requires an infinitive, usually to + base verb.',
    items:[
      ['The company plans to _____ a new support center.', ['open','opened','opening','opens'], 'A'],
      ['Ms. Li agreed to _____ the revised contract.', ['review','reviewed','reviewing','reviews'], 'A'],
      ['The supplier promised to _____ the missing items by Friday.', ['ship','shipped','shipping','ships'], 'A'],
      ['Employees are encouraged to _____ questions during the session.', ['ask','asked','asking','asks'], 'A'],
      ['The team hopes to _____ the project before December.', ['finish','finished','finishing','finishes'], 'A'],
      ['The director decided to _____ the announcement until Monday.', ['postpone','postponed','postponing','postpones'], 'A'],
      ['Please remember to _____ the form before submitting it.', ['sign','signed','signing','signs'], 'A'],
      ['The department intends to _____ two additional interns.', ['hire','hired','hiring','hires'], 'A'],
    ],
  },
  {
    id:'preposition.time', skills:['preposition'], chapterIds:[12], difficulty:2,
    explanation:'Choose the time preposition that matches the relationship: deadline, period, starting point, or duration.',
    items:[
      ['All expense reports must be submitted _____ Friday afternoon.', ['by','during','among','beside'], 'A'],
      ['The office will remain closed _____ the public holiday.', ['during','by','among','beside'], 'A'],
      ['The refund will be processed _____ five business days.', ['within','during','among','toward'], 'A'],
      ['The discount is valid _____ the end of the month.', ['until','among','beside','across'], 'A'],
      ['The new policy takes effect _____ October 1.', ['on','in','at','by'], 'A'],
      ['The seminar begins _____ 9:30 A.M.', ['at','on','in','during'], 'A'],
      ['The company has used this system _____ 2022.', ['since','for','during','by'], 'A'],
      ['The warranty is valid _____ two years from the purchase date.', ['for','since','by','at'], 'A'],
    ],
  },
  {
    id:'preposition.verb-collocation', skills:['preposition','collocation'], chapterIds:[13], difficulty:3,
    explanation:'This is a fixed verb/adjective + preposition combination and should be learned as one chunk.',
    items:[
      ['The new procedure applies _____ all regional offices.', ['to','for','at','with'], 'A'],
      ['Please refer _____ the attached chart for current prices.', ['to','at','from','by'], 'A'],
      ['The company invested heavily _____ automated equipment.', ['in','at','of','by'], 'A'],
      ['All employees must comply _____ the updated safety rules.', ['with','to','for','at'], 'A'],
      ['Ms. Ahmed will speak _____ behalf of the regional office.', ['on','in','at','for'], 'A'],
      ['The team participated _____ a two-day training workshop.', ['in','at','for','to'], 'A'],
      ['The delay resulted _____ a shortage of raw materials.', ['from','in','at','to'], 'A'],
      ['The new process resulted _____ shorter waiting times.', ['in','from','at','of'], 'A'],
    ],
  },
  {
    id:'connector.clause-vs-phrase', skills:['conjunction','preposition'], chapterIds:[19], difficulty:4,
    explanation:'Check what follows the blank: conjunctions such as because/although take a clause, while because of/despite take a noun phrase.',
    items:[
      ['The delivery was delayed _____ severe weather near the port.', ['because','because of','although','unless'], 'B'],
      ['The delivery was delayed _____ the weather was severe near the port.', ['because','because of','despite','during'], 'A'],
      ['_____ the limited budget, the team completed the project.', ['Although','Despite','Because','Unless'], 'B'],
      ['_____ the budget was limited, the team completed the project.', ['Although','Despite','Because of','During'], 'A'],
      ['The store remained busy _____ the higher prices.', ['despite','although','because','unless'], 'A'],
      ['The store remained busy _____ prices had increased.', ['although','despite','because of','during'], 'A'],
      ['Production stopped _____ a mechanical failure.', ['because of','because','although','unless'], 'A'],
      ['Production stopped _____ a machine had failed.', ['because','because of','despite','during'], 'A'],
    ],
  },
  {
    id:'connector.condition-purpose', skills:['conjunction'], chapterIds:[16,19], difficulty:3,
    explanation:'Identify the logical relationship first: condition, purpose, reason, contrast, or time.',
    items:[
      ['The seminar will be postponed _____ the speaker cannot travel.', ['if','although','so that','because of'], 'A'],
      ['Ms. Lee arrived early _____ she could test the projector.', ['so that','unless','whereas','despite'], 'A'],
      ['The contract will remain valid _____ both parties agree to terminate it.', ['until','because','whereas','therefore'], 'A'],
      ['The company will expand the pilot _____ the results remain positive.', ['as long as','despite','because of','whereas'], 'A'],
      ['Please contact IT _____ you experience any login problems.', ['if','despite','during','because of'], 'A'],
      ['The team added another shift _____ meet the increased demand.', ['in order to','although','unless','because'], 'A'],
      ['We will send the itinerary _____ all reservations are confirmed.', ['once','despite','because of','whereas'], 'A'],
      ['The outdoor event will continue _____ the weather becomes unsafe.', ['unless','because','although','so that'], 'A'],
    ],
  },
  {
    id:'relative.pronouns', skills:['relative-clause'], chapterIds:[9], difficulty:3,
    explanation:'Choose the relative word based on the antecedent and its grammatical role in the clause.',
    items:[
      ['The employee _____ organized the event received an award.', ['which','who','whose','where'], 'B'],
      ['The building _____ roof was damaged will remain closed.', ['who','which','whose','where'], 'C'],
      ['The warehouse, _____ opened last year, is already full.', ['who','which','where','what'], 'B'],
      ['The city _____ the conference is held has a large convention center.', ['which','where','who','whose'], 'B'],
      ['The consultant with _____ we met recommended another supplier.', ['who','whom','which','whose'], 'B'],
      ['The report _____ was submitted yesterday contains the final figures.', ['who','which','where','whose'], 'B'],
      ['The manager _____ team exceeded its target received a bonus.', ['who','which','whose','where'], 'C'],
      ['The office _____ Ms. Patel works is on the sixth floor.', ['which','where','who','whose'], 'B'],
    ],
  },
  {
    id:'pronoun.forms', skills:['pronoun'], chapterIds:[8], difficulty:2,
    explanation:'Choose the pronoun form that matches the blank’s job: subject, object, possessive adjective, possessive pronoun, or reflexive.',
    items:[
      ['Employees should keep _____ ID cards visible at all times.', ['they','their','theirs','them'], 'B'],
      ['Managers should familiarize _____ with the updated policy.', ['them','their','themselves','theirs'], 'C'],
      ['The revised proposal is more detailed than _____ submitted last month.', ['that','those','them','itself'], 'A'],
      ['The two designs are similar, but _____ is less expensive.', ['one','ones','themselves','each other'], 'A'],
      ['Please send the completed forms directly to _____.', ['we','us','our','ours'], 'B'],
      ['The new laptops are faster than _____ used last year.', ['those','that','them','themselves'], 'A'],
      ['Ms. Chen completed the entire report by _____.', ['her','hers','herself','she'], 'C'],
      ['The company revised _____ travel policy last week.', ['it','its','itself','theirs'], 'B'],
    ],
  },
  {
    id:'comparison.patterns', skills:['comparison'], chapterIds:[18], difficulty:3,
    explanation:'Use comparison signals such as than, as...as, and group size to choose comparative, equality, or superlative structures.',
    items:[
      ['This quarter’s sales were significantly _____ than expected.', ['high','higher','highest','highly'], 'B'],
      ['The new office is not as spacious _____ the previous location.', ['than','as','like','from'], 'B'],
      ['Of the four proposals, this one is the _____ practical.', ['more','most','much','very'], 'B'],
      ['The new warehouse is nearly twice as large _____ the old one.', ['than','as','like','from'], 'B'],
      ['The updated software runs considerably _____ than before.', ['smooth','more smoothly','smoothest','smoothly more'], 'B'],
      ['This model is one of the _____ reliable printers we have tested.', ['more','most','much','very'], 'B'],
      ['Delivery by rail is generally _____ expensive than air freight.', ['less','least','little','few'], 'A'],
      ['The premium plan offers _____ features than the basic plan.', ['many','more','most','much'], 'B'],
    ],
  },
  {
    id:'participle.feeling', skills:['part-of-speech'], chapterIds:[15], difficulty:2,
    explanation:'Use -ing for something that causes a feeling and -ed for the person or thing experiencing that feeling.',
    items:[
      ['The revised training program is more _____ than the previous one.', ['engaged','engaging','engage','engagement'], 'B'],
      ['Employees were _____ by the sudden schedule change.', ['surprising','surprised','surprise','surprisingly'], 'B'],
      ['The orientation video was informative but not very _____.', ['excited','exciting','excitement','excite'], 'B'],
      ['Several applicants were _____ about the new interview procedure.', ['confusing','confused','confuse','confusion'], 'B'],
      ['The long delay was extremely _____ for customers.', ['frustrated','frustrating','frustrate','frustration'], 'B'],
      ['The audience seemed _____ by the speaker’s explanation.', ['interested','interesting','interest','interestingly'], 'A'],
      ['The repeated system errors have become increasingly _____.', ['annoyed','annoying','annoy','annoyance'], 'B'],
      ['The staff felt _____ after completing the overnight inventory.', ['tiring','tired','tire','tiredly'], 'B'],
    ],
  },
  {
    id:'vocab.business-collocation', skills:['vocabulary','collocation'], chapterIds:[21,26], difficulty:3,
    explanation:'Choose the word that forms the natural business collocation and fits the meaning of the sentence.',
    items:[
      ['The company will _____ a customer survey next week.', ['conduct','construct','contain','contact'], 'A'],
      ['Please keep the receipt as _____ of purchase.', ['proof','permission','advice','approval'], 'A'],
      ['The retailer plans to _____ a new loyalty program in November.', ['launch','land','lend','lift'], 'A'],
      ['The board decided to _____ the decision until more data were available.', ['postpone','preserve','predict','purchase'], 'A'],
      ['The campaign is intended to _____ brand awareness.', ['raise','rise','arise','lifted'], 'A'],
      ['The manufacturer issued a product _____ after discovering a defect.', ['recall','receipt','retreat','returning'], 'A'],
      ['The new procedure should _____ the approval process.', ['streamline','stream','straighten up','strength'], 'A'],
      ['The agreement clearly _____ the responsibilities of both parties.', ['outlines','outcomes','outgrows','outweighs'], 'A'],
    ],
  },
]

export const extraPart5V4: Question[] = rules.flatMap((rule, ruleIndex) =>
  rule.items.map((item, itemIndex) => ({
    id: `p5-v4-${String(ruleIndex + 1).padStart(2, '0')}-${String(itemIndex + 1).padStart(2, '0')}`,
    part: 5 as const,
    stem: item[0],
    choices: c(...item[1]),
    answer: item[2],
    skills: rule.skills,
    difficulty: rule.difficulty,
    explanation: rule.explanation,
    ruleId: rule.id,
    chapterIds: rule.chapterIds,
    targetSeconds: rule.difficulty >= 4 ? 35 : rule.difficulty >= 3 ? 30 : 25,
  })),
)
