import type { Question, SkillId, TrainerState } from './types'
import { courseChapters, skillChapterIds } from './courseGuide'

// Original explanations and memory cues; page references point to the learner's local PDFs.
// Keep one recall task per card, rather than reproducing worksheets or their artwork.
export const courseSources = [
  ...courseChapters,
  {id:22,title:'Listening · Photographs',file:'Chapter22-Listening Part 1 Photographs.pdf'},
  {id:23,title:'Listening · Question–Response',file:'Chapter23-Listening-Part2-QuestionResponse.pdf'},
  {id:24,title:'Listening · Conversations',file:'Chapter24-Listening-Part3-ShortCon.pdf'},
  {id:25,title:'Listening · Short Talks',file:'Chapter25-Part4-ShortTalks.pdf'},
  {id:29,title:'แนวข้อสอบรวม',file:'ข้อสอบ TOEIC.pdf'},
  {id:30,title:'โน้ตที่ต้องจำเพิ่ม',file:'สิ่งที่ต้องจำเพิ่ม.pdf'},
].sort((a,b)=>a.id-b.id)

export interface CourseCard {
  id: string
  chapter: number
  pages: string
  title: string
  memory: string
  patterns: string[]
  example: string
  prompt: string
  answer: string
}

const cards = `
1|1|หา N. จากหน้าที่|นามมีสามที่: เป็นประธาน เป็นกรรม ตามหลังบุพบท|N. → V.;V. → N.;Prep. → N./V-ing|The supervisor approved the request after lunch.|after _____ : ต้องมองหาหน้าที่อะไร?|นามหรือกลุ่มนาม เช่น after lunch ไม่ใช่กริยาที่ผันแล้ว
1|1–3|กลุ่มท้ายคำที่ชวนให้นึกถึง N.|แบ่งจำสามชุด แล้วกลับไปเช็กตำแหน่งจริงเสมอ|กลุ่ม 1 → -tion / -ment / -dom / -ship / -nce;กลุ่ม 2 → -ty / -ism / -ness;กลุ่ม 3 → -age / -sis / -hood|The announcement increased customer awareness.|awareness เป็นชนิดอะไร และดูจากอะไร?|N. จาก -ness และเป็นกรรมของ increased; suffix เป็นเบาะแส ไม่ใช่กฎไร้ข้อยกเว้น
1|3|คนทำ vs คนรับ|er/or มักทำ • ee มักรับ; จำจากคำที่รู้จักก่อน|interviewer → ผู้สัมภาษณ์;interviewee → ผู้ถูกสัมภาษณ์;คน / อาชีพ → -ant / -ist / -ian / -ent|The interviewer greeted each interviewee.|trainee กับ trainer ต่างกันอย่างไร?|trainee ผู้ฝึกงานหรือผู้รับการฝึก; trainer ผู้ฝึกสอน
2|1–4|นับได้หนึ่ง / หลาย / นับไม่ได้|ดูนามก่อน แล้วเลือกตัวนำหน้า|a/an/each/every/another → นับได้เอกพจน์;many/several/few/these → นับได้พหูพจน์;much/little/less → นับไม่ได้;a lot of/some/the → ใช้ได้หลายกลุ่ม|Each applicant must provide a copy of the certificate.|each applicants แก้อย่างไร?|each applicant; each ตามด้วยนามนับได้เอกพจน์ ส่วน a lot of ใช้กับ water ได้ด้วย
2|3–4|a / an / the ใช้เสียง|หูเลือก a/an • บริบทเลือก the|a → เสียงพยัญชนะ;an → เสียงสระ;the → คนอ่านรู้ว่าหมายถึงสิ่งใด|An experienced analyst works at a university.|a university แต่ an hour เพราะอะไร?|university เริ่มเสียง /y/; hour ไม่ออกเสียง h; ดูเสียง ไม่ใช่ตัวอักษรแรก
2|6–10|much / many + some / any|many นับหลาย • much นับไม่ได้; เสนอให้มักใช้ some|many → documents;much → equipment / information;some → บอกเล่า / เสนอ / ขอ;any → ปฏิเสธ / คำถามทั่วไป / ใดก็ได้|Would you like some water before the interview?|much informations ถูกไหม?|ไม่ถูก: information นับไม่ได้ ใช้ much information; อย่าตัด some ทิ้งในคำถามเสนอให้
2|8–9|every / some / no / any + one/body/thing|สิบสองคำ รวมเป็นหนึ่งประธาน|everyone/somebody/nothing/anything → V. เอกพจน์;does → V. ไม่ผัน|Everyone in the department has received the memo.|Everyone have หรือ has?|has; in the department เป็นส่วนขยาย ไม่ได้ทำให้ประธานเป็นพหูพจน์
2|11–12|another / other / others / the other|another อีกหนึ่ง • others ยืนเอง • the other ที่เหลือ|another → N. เอกพจน์;other → N. พหูพจน์ / นับไม่ได้;others → ไม่มี N. ตาม;the other → อีกหนึ่งในสอง / ส่วนที่เหลือ|One printer is broken; the other is working.|others employees แก้อย่างไร?|other employees; others เป็นสรรพนามอยู่แล้ว อีกทั้ง another two days เป็นโครงสร้างพิเศษที่ใช้ได้
2|14–15|no / not / never / none|no นำ N. • none แทน N. • never บอกไม่เคย|no → noun;auxiliary + not → verb;never → ก่อน V. หลัก / หลัง be;none → ยืนเอง หรือ of + กลุ่มนาม|No invoices are missing. None of them are overdue.|no approve ใช้ได้ไหม?|ไม่ได้: does not approve / never approves; no approval ใช้ได้เพราะ approval เป็นนาม
3|1–3|Adj. มีสามบ้าน|หน้านาม • หลัง be • หลัง linking verb|Adj. → N.;be → Adj.;look/seem/remain/become → Adj.|The revised policy seems reasonable.|seems reasonably แก้อย่างไร?|seems reasonable เพราะบอกสภาพของ policy; reasonably อาจขยาย Adj. ที่ตามมา เช่น reasonably clear
3|2|ท้ายคำ Adj. และข้อยกเว้น|al • ble • ous • ful • less • ic • ish • tive|reliable → -ble;successful → -ful;competitive → -tive;friendly → Adj. แม้ลงท้าย -ly|A reliable supplier delivered the goods.|friendly เป็น Adv. เพราะ -ly ไหม?|ไม่ใช่ เป็น Adj.; ต้องยืนยันด้วยตำแหน่งและความหมาย
3|3–4|tall / high • alone / lonely|tall วัดความสูงตัวสิ่ง • high ระดับ; alone สถานะ • lonely ความรู้สึก|tall → building / person;high → score / price / altitude;alone → อยู่คนเดียว;lonely → รู้สึกเหงา|The analyst works alone but does not feel lonely.|คะแนนสูงใช้ tall score หรือ high score?|high score; alone ไม่ได้แปลว่ารู้สึกเหงาเสมอไป
4|1–2|โจทย์ตระกูลคำ เริ่มที่โครงสร้าง|อย่าแปลทุกช้อยซ์ก่อน: หาประธาน กริยา และนามข้างช่องว่าง|อ่านทั้งประโยค → หา S. / V.;ดูรอบช่องว่าง → ต้องการ N./Adj./Adv./V.;ค่อยเช็ก → ความหมาย / รูปคำ|Their _____ improved after the training. (perform / performance)|ช่องว่างต้องการอะไร?|performance เป็นหัวนามของประธาน Their performance; improved เป็นกริยาหลักแล้ว
5|1–3|Adv. ขยายสามชนิด|กริยา • คุณศัพท์ • วิเศษณ์|V. → Adv.;Adv. → Adj.;Adv. → Adv.|The team responded very quickly to the request.|very กับ quickly ขยายอะไร?|very ขยาย quickly; quickly ขยาย responded จึงเป็น Adv. ทั้งคู่
5|2–5|ห้าจุดวาง Adv.|ดูสิ่งที่มันขยาย มากกว่าจำว่าอยู่ติดคำไหน|S. → Adv. → V.;auxiliary → Adv. → main V.;V. → Adv.;Det. → Adv. → Adj. → N.;be + V3 → Adv.|The shipment was carefully inspected.|carefully อยู่คั่นอะไร?|was กับ inspected; ขยายการตรวจ ไม่ใช่ shipment
5|1–2|Adv. ไม่ได้ลงท้าย ly ทุกคำ|fast / hard / late ใช้ได้หลายหน้าที่|fast → Adj. / Adv.;hard → หนัก / อย่างหนัก;hardly → แทบไม่;late → สาย;lately → ช่วงนี้|The staff worked hard and hardly took a break.|worked hardly หมายถึงทำงานหนักไหม?|ไม่ใช่ hardly แปลว่าแทบไม่; worked hard จึงหมายถึงทำงานหนัก
6|1–4|แผนที่ประโยคก่อนเลือกชนิดคำ|หาแกน S + V แล้วค่อยต่อส่วนขยาย|Det. → (Adv. + Adj.) → N.;N. → V. → O.;Prep. → N./V-ing|The highly skilled engineers completed the inspection carefully.|highly skilled engineers ใครเป็นหัวคำ?|engineers เป็น N. หัวประธาน; skilled เป็น Adj.; highly เป็น Adv. ขยาย skilled
7|1–3|รู้จักตระกูล V.|ize / en / ify ช่วยเดา แต่ตำแหน่งช่วยตัดสิน|organize / realize → -ize;widen / shorten → -en;identify / notify → -ify;design / submit / support → จำเป็นคำ|The company plans to modernize its equipment.|หลัง plans to ต้องการ modern / modernize?|modernize เป็น V. ไม่ผัน; modern เป็น Adj.
7|3–10|กริยาช่วยจับคู่รูป|do + one • have + done • be + ing / V3|do/does/did/modal → V. ไม่ผัน;have/has/had → V3 ใน perfect;be → V-ing ถ้ากำลังทำ;be → V3 ถ้าถูกทำ|The invoices have been reviewed.|have been reviewed เป็นโครงสร้างใด?|perfect passive: have + been (V3 ของ be) + reviewed; have เป็นกริยาหลักก็รับนามได้ เช่น have a meeting
8|1–5|Pronoun ห้าช่อง|ประธาน • กรรม • ของ+N. • ของยืนเอง • ตัวเอง|I → me → my → mine → myself;we → us → our → ours → ourselves;they → them → their → theirs → themselves;he → him → his → his → himself;she → her → her → hers → herself;you → you → your → yours → yourself/yourselves;it → it → its → — → itself|She sent us her proposal; the final decision is ours.|her proposal กับ hers ต่างอย่างไร?|her ต้องมี N. ตาม; hers ยืนแทนนามได้ เช่น The proposal is hers.
8|5|reflexive กับ by oneself|คนเดียวกับประธานใช้ self • by self ทำเอง|blame oneself → ตำหนิตัวเอง;by oneself → ด้วยตัวเอง / ลำพัง|The technicians repaired the unit by themselves.|by their หรือ by themselves?|by themselves; their ต้องมีนามตาม
9|1–8|Relative: ดูนามหน้า + สิ่งที่ขาดหลัง|คน who/whom • ของ which • เจ้าของ whose|คน + who/that → V.;คน + whom/that → S. + V.;ของ + which/that → ประธาน / กรรม;whose → N.|The consultant whose report won the award will speak today.|whose หลังมองอะไร?|มอง report ซึ่งเป็นนาม; whose บอกว่าเป็นรายงานของ consultant
9|5–8|where / when / why|สถานที่ วันเวลา เหตุผล: เช็กว่าหลังเป็นประโยคครบ|place + where → S. + V.;time + when → S. + V.;reason + why → S. + V.|This is the office where we held the interview.|office which we rented กับ office where we worked ต่างอย่างไร?|rented ขาดกรรม จึงใช้ which; worked ไม่ขาดกรรม ต้องการสถานที่จึงใช้ where
9|4–5|Wh-question และ How|what/which/whose ดูนาม • how ดูลักษณะ|how long → ระยะเวลา / ความยาว;how far → ระยะทาง;how many → จำนวนที่นับได้;how much → ปริมาณ / ราคา;how often → ความถี่|How often is the equipment inspected?|Twice a month ตอบ How ตัวไหน?|How often; อย่าสับสนกับ How long ที่ถามระยะเวลา
10|1–3|หาประธานตัวจริง|ตัดกลุ่มขยายในใจ แล้วจับหัวนามกับกริยา|หัวประธาน → ข้าม Prep. phrase;หัวประธาน → ข้าม relative clause;he/she/it → V-s ใน present simple|The list of required documents is on the website.|documents หลายชิ้น ทำไมใช้ is?|หัวประธานคือ list เอกพจน์; of required documents ขยาย list
11|1–7|12 Tenses แบบต่อชิ้น|เลือกเวลา แล้วเลือก simple / continuous / perfect|อดีต → V2 / was-were / had;ปัจจุบัน → V1 / am-is-are / have-has;อนาคต → will;continuous → be + ing;perfect → have + V3;perfect continuous → have + been + ing|By next Friday, we will have completed the audit.|will have been working คือ Tense อะไร?|Future perfect continuous; will บอกอนาคต และ have been + ing บอกต่อเนื่องถึงจุดนั้น
11|8–14|Simple: นิสัยหรืออดีตจบแล้ว|ทุกวันดู V1 • ago/last/yesterday ดู V2|usually/regularly/every → นิสัย;last/yesterday/ago → อดีตจบแล้ว;V2 → เป็นกริยาผันเอง;V3 → ใช้กับ auxiliary ใน perfect/passive|The branch opened two months ago.|opened เป็น V2 หรือ V3 ในประโยคนี้?|V2 เป็นกริยาหลัก ไม่มี have/be นำ; รูป -ed เหมือนกันได้ ต้องดูหน้าที่
11|18–22|Continuous: เหตุการณ์กำลังดำเนิน|ตอนนี้ is doing • ตอนนั้น was doing • ตอนหน้า will be doing|now/currently → am/is/are + ing;while + กำลังเกิดในอดีต → was/were + ing;เวลาหนึ่งในอนาคต → will be + ing|We were reviewing the contract when the client called.|เหตุการณ์ไหนกำลังเกิด เหตุการณ์ไหนแทรก?|were reviewing กำลังตรวจ; called เกิดแทรก แต่ while ไม่ได้บังคับ continuous ทุกบริบท
11|23–27|Present Perfect: อดีตโยงตอนนี้|have/has + V3 • since จุด • for ช่วง|since → จุดเริ่ม;for → ระยะเวลา;already/just/yet → ดูผลและบริบท;during → ระหว่างเหตุการณ์|The firm has operated here since 2018.|since 2018 กับ for eight years ใช้ต่างอย่างไร?|since ระบุจุดเริ่ม; for ระบุระยะเวลา; ทั้งคู่ใช้ได้กับ perfect แต่ไม่ได้บังคับ perfect ทุกประโยค
11|28–32|Perfect: เสร็จก่อนอีกจุดเวลา|อดีตก่อนใช้ had • อนาคตก่อนใช้ will have|เหตุการณ์ก่อนในอดีต → had + V3;เหตุการณ์หลัง → V2;เสร็จก่อนจุดอนาคต → will have + V3|The team had submitted the bid before the office closed.|อะไรเกิดก่อน?|submitted the bid เกิดก่อน closed; อย่าเลือก had เพียงเพราะเห็น before โดยไม่ดูเหตุการณ์
11|33–36|Perfect vs Perfect Continuous|ผลลัพธ์ / จำนวน vs การทำต่อเนื่อง|have + V3 → เน้นผล;have been + ing → เน้นระยะ / กิจกรรมต่อเนื่อง;stative verbs → มักไม่ใช้ continuous|She has written three reports. She has been writing all morning.|ประโยคไหนเน้นงานเสร็จสามฉบับ?|has written three reports; ทั้งสองโครงสร้างรับ since/for ได้ในบริบทที่เหมาะสม
12|1–6|in / on / at เวลาและสถานที่|ใหญ่ใน in • วันบน on • จุดที่ at|in → เดือน ปี เมือง ห้อง;on → วัน วันที่ พื้นผิว ถนน;at → เวลา จุดนัด ที่อยู่ละเอียด|The seminar begins at 9 on Monday in June.|Monday morning ใช้ in หรือ on?|on Monday morning; in the morning ใช้เมื่อไม่ได้ระบุวัน
12|2–3,9–12|by / within / during / upon|by เส้นตาย • within ภายในช่วง • during ระหว่างงาน|by → deadline;within → ระยะเวลา;during → event/period;upon → เมื่อเกิด / เมื่อได้รับ|Please reply within three working days.|by Friday ต่างจาก within three days อย่างไร?|by ระบุจุดเส้นตาย; within ระบุความยาวนับจากจุดเริ่มในบริบท
12|4–15|สำนวน in / on / at / by|ท่องเป็นกลุ่มใช้จริง ไม่ท่องแค่คำแปล|in → advance / writing / cash / general / my opinion;on → time / purpose / sale / business / vacation;at → present / the moment / night;by → mistake / chance / accident / credit card / car;on → foot / the phone / the internet|The order was placed by mistake, not on purpose.|จ่ายเงินสดกับบัตรใช้บุพบทอะไร?|in cash; by credit card; เดินเท้า on foot ต่างจาก by car
12|1–2,19–22|ทิศทางและตำแหน่ง|into เคลื่อนเข้า • inside อยู่ใน; through ผ่าน • throughout ทั่ว|over/above → เหนือ;under/below → ใต้;beside/next to → ข้าง;behind → หลัง;across → ข้าม;along → ตามแนวยาว|The courier walked through the lobby into the office.|through ต่างจาก throughout อย่างไร?|through ผ่านจากทางหนึ่งไปอีกทาง; throughout ทั่วบริเวณหรือช่วงเวลา
12|3,9,12|คู่ที่ชอบสลับ|in time ทัน • on time ตรง; at end จุด • in end ผล|in time → ทันก่อนสาย;on time → ตามกำหนด;in the end → ในที่สุด;at the end → ตอนท้าย|The parcel arrived in time for the exhibition.|in time แปลว่ามาก่อนเสมอไหม?|หมายถึงทันเวลาสำหรับสิ่งหนึ่ง อาจก่อนเส้นตายหรือพอดี; on time เน้นตรงกำหนด
13|1–11|V. + Prep. อย่าจำแยก|นึกเป็น chunk: คำหน้าช่วยเรียกคำหลัง|rely → on;participate → in;subscribe → to;deal → with;complain → about;apply → for;consist → of;benefit → from|We rely on the supplier to deliver on time.|discuss about the plan ถูกไหม?|ใช้ discuss the plan; หรือ discuss the plan with someone ไม่เติม about หน้าเรื่อง
14|1–4|Active / Passive|ถามว่า S. ทำเองหรือรับการกระทำ แล้วเลือกเวลา|active → S. ทำ;passive → S. รับ;passive → be + V3;perfect passive → have + been + V3|The invoice was issued yesterday.|invoice issued yesterday ขาดอะไร?|ถ้าเป็นประโยคหลัก ขาด was; แต่ the invoice issued yesterday อาจเป็นกลุ่มนามที่ยังต้องมีกริยาหลักตาม
15|1–7|ing / ed ความรู้สึก vs การกระทำ|น่ารู้สึก ing • รู้สึก ed; เช็กผู้ทำ / ผู้รับด้วย|interesting → ทำให้น่าสนใจ;interested → รู้สึกสนใจ;processing → กำลังดำเนินการ;processed → ถูกดำเนินการ|The staff are interested in the new training program.|คนใช้ ing ได้ไหม?|ได้ เช่น an interesting speaker; อย่าจำว่าคนต้อง ed เสมอ ให้ดูความหมายและหน้าที่
15|8–11|Participle หลัง N.|แกนประโยคครบแล้ว ส่วนนี้ขยายนาม|N. + V-ing → นามทำเอง;N. + V3 → นามถูกทำ;by → เบาะแสผู้กระทำ|The documents submitted yesterday require approval.|ทำไมไม่ใช้ were submitted ในช่องขยายนามนี้?|require เป็น V. หลักแล้ว; submitted yesterday เป็นส่วนขยายย่อจาก that were submitted yesterday
16|1–4|If สามภาพเวลา|จริงข้างหน้า • สมมติตอนนี้ • ย้อนอดีต|if + V1 → will + V1;if + V2 → would + V1;if + had V3 → would have V3|If we had booked earlier, we would have received a discount.|had booked จับคู่ผลแบบใด?|would have received; เป็นอดีตที่ไม่ได้เกิดจริง ไม่ใช่ would receive
17|1–5|Gerund คือ N. จาก V-ing|เป็นประธาน เป็นกรรม ตามหลัง Prep.|V-ing → ประธาน;enjoy/avoid/consider/admit → V-ing;mind/finish/keep/quit/resist → V-ing;spend/waste time → V-ing|They considered relocating the office.|consider to relocate แก้อย่างไร?|consider relocating; เลือกตาม verb pattern ของคำหน้า
17|2–5|to ที่เป็น Prep. + ing|มองทั้งสำนวนก่อนตัดสินว่า to คืออะไร|look forward to → V-ing;be used/accustomed to → V-ing;object/be opposed to → V-ing;be devoted/dedicated/addicted to → V-ing|We look forward to meeting your team.|ทำไมไม่ใช้ meet หลัง to?|to ใน look forward to เป็นบุพบท ไม่ใช่ infinitive marker
17|7–10|to-infinitive + คน + to|want/plan/agree ต่อยอดด้วย to V1|agree/decide/plan/promise/offer → to V1;afford/attempt/fail/hope/learn → to V1;ask/allow/advise/encourage → คน + to V1|The supervisor encouraged us to apply.|encouraged us applying แก้อย่างไร?|encouraged us to apply; มีกรรม us ก่อน infinitive
17|10–12|used to / be used to / stop|เคยทำ V1 • คุ้นเคย ing; หยุดทำ vs หยุดเพื่อทำ|used to → V1;be used to → N./V-ing;stop doing → เลิกทำ;stop to do → หยุดสิ่งเดิมเพื่อทำอีกอย่าง|She used to commute; now she is used to working remotely.|is used to work ถูกไหมในความหมายคุ้นเคย?|ต้องใช้ is used to working; used to work ไม่มี be หมายถึงเคยทำ
18|1–8|สามระดับ เปรียบเทียบ|เท่ากัน as-as • สองฝ่ายกว่า • ทั้งกลุ่มที่สุด|as → Adj./Adv. ขั้นปกติ → as;comparative → -er / more → than;superlative → -est / most;much/even/far → ขยาย comparative|This method is much more efficient than the old one.|much efficient แก้อย่างไร?|much more efficient; much ขยายขั้นกว่า ในที่นี้ efficient บอกคุณสมบัติ method
18|2–3|ผันไม่ปกติและข้อยกเว้น|good better best • bad worse worst|good/well → better → best;bad/badly → worse → worst;much/many → more → most;little → less → least;few → fewer → fewest;far → farther/further|The revised estimate is better than the original.|more better ถูกไหม?|ไม่ถูก better เป็นขั้นกว่าแล้ว; คำสองพยางค์ไม่ได้ใช้ more ทุกคำ เช่น easier
19|1–8|Connector ดูสิ่งที่ตามหลัง|because ครบ S+V • because of กลุ่ม N.|because/although → clause;because of/despite → N./V-ing;before/after/until → ตรวจว่าเป็น clause หรือกลุ่มนาม|Although the price rose, demand remained strong.|despite the price rose แก้อย่างไร?|although the price rose หรือ despite the price increase; despite เป็นบุพบท
19|3–7|เหตุผล เวลา เงื่อนไข|เพราะ • เมื่อ • แม้ • ถ้า • เผื่อ • ถ้าไม่|because/since/as/now that → เหตุผล;when/once/as soon as → เวลา;although/though/even though → แม้;if/provided that → เงื่อนไข;in case → เผื่อ;unless → if not;so that/in order that → เพื่อให้|Keep the receipt in case you need a refund.|unless ต่างจาก in case อย่างไร?|unless ถ้าไม่; in case เตรียมเผื่อสิ่งหนึ่งเกิด ไม่ใช่เงื่อนไขเดียวกัน
19|8–17|however / therefore: เช็กวรรคตอน|Adv. เชื่อมความคิด แต่แทน Conj. ไม่ได้ทุกตำแหน่ง|however/nevertheless → ขัดแย้ง;therefore/thus/consequently → ผล;moreover/furthermore/additionally → เพิ่ม;otherwise → มิฉะนั้น;for example/for instance → ตัวอย่าง;S+V; however, S+V → โครงสร้างใช้ได้|The price rose. However, demand remained strong.|ตัด however ทิ้งทุกข้อได้ไหม?|ไม่ได้: ดูประโยคสมบูรณ์และวรรคตอนก่อน; however ไม่ทำให้สองประโยคเชื่อมด้วย comma อย่างเดียวได้
19|12–13|FANBOYS + คู่เชื่อม|for and nor but or yet so • โครงสร้างสองข้างขนานกัน|both → and;either → or;neither → nor;not only → but also;yet → แต่;S+V, FANBOYS S+V → เชื่อมประโยค|Applicants may submit either a résumé or a portfolio.|both ... or แก้อย่างไร?|both ... and หรือ either ... or; หลังสองฝั่งควรเป็นโครงสร้างชนิดเดียวกัน
20|1–3|Question Tag|สลับบวก–ลบ • ใช้ auxiliary เดิม • pronoun ตรง S.|positive → negative tag;negative → positive tag;present simple ไม่มี auxiliary → do/does|The shipment has arrived, hasn't it?|has arrived จบ tag ว่า doesn't it ได้ไหม?|ใช้ hasn't it; auxiliary คือ has ไม่ใช่ does
21|1–5|Business: เล่าเป็นลำดับงาน|อนุมัติ → ใช้แผน → ตรวจ → ประเมิน → รับรู้ผล|authorize → ให้อำนาจ;implement → นำมาใช้;audit → ตรวจบัญชี;assess/appraise/evaluate → ประเมิน;acknowledge/appreciate → รับรู้ / เห็นคุณค่า|The manager authorized the purchase after evaluating the proposal.|audit กับ evaluate ต่างอย่างไร?|audit เน้นตรวจหลักฐาน/บัญชี; evaluate ประเมินคุณค่า จึงแทนกันไม่ได้ทุกบริบท
21|7–10|Sales: เดินทางของสินค้า|order → ship → deliver → receipt → refund|goods/merchandise → สินค้า;wholesale → ค้าส่ง;stock/inventory → สินค้าคงคลัง;sale → การลดราคา / การขายครั้งหนึ่ง;sales → ยอดขาย / งานขาย;reimbursement → คืนค่าใช้จ่าย|Keep the receipt to request a refund.|refund กับ reimbursement ต่างอย่างไร?|refund คืนเงินที่ชำระ; reimbursement ชดเชยค่าใช้จ่ายที่ออกไปก่อน
21|11–16|Adj. ต้องจับคู่สิ่งที่ขยาย|สำคัญ • เป็นไปได้ • มาก/น้อย • พร้อมใช้งาน|essential/mandatory/imperative → จำเป็น;possible/likely → เป็นไปได้;available → มีให้ใช้;affordable → ราคาเข้าถึงได้;capable of → สามารถ;responsible for → รับผิดชอบ|The equipment is available, but it is not affordable for every branch.|available แทน affordable ได้ไหม?|ไม่ได้: available มีให้ใช้/หาได้; affordable ราคาไม่เกินกำลังจ่าย
21|17–18|กลุ่ม ive จำตามงาน|สร้าง → แข่งขัน → ทำผล → ร่วมมือ → ตอบรับ|creative/innovative → สร้างสรรค์;competitive → แข่งขันได้;effective → ได้ผล;productive → ให้ผลงานมาก;collaborative → ร่วมมือ;responsive → ตอบสนอง|The new process is effective and helps the team be more productive.|effective กับ productive เหมือนกันทุกกรณีไหม?|ไม่เหมือน: effective บรรลุผล; productive ผลิตผลงานได้มาก ควรดูนามและสถานการณ์
21|19–23,39–40|ศัพท์ ed + คำต่อ|อย่าหยุดที่คำแปล: จำสิ่งที่ตามได้ด้วย|required/expected/allowed → to V1;interested/specialized → in;equipped/satisfied → with;qualified/prepared → for;directed → to;admitted → to/into|Visitors are required to present identification.|required + presenting ได้ไหม?|ในความหมายถูกกำหนดให้ทำ ใช้ required to present; มีรูป required for + N. ในบริบทอื่น
21|24–28|สมัคร / เข้าร่วม / เข้าอาคาร|งาน for • เรียน in • สมาชิก to • กิจกรรม in|apply for → งาน;enroll in → หลักสูตร;subscribe to → สมาชิก;sign up/register for → ลงทะเบียน;participate in → กิจกรรม;attend → งาน/ประชุม ไม่เติม in;enter → อาคาร ไม่เติม into ในโครงสร้างทั่วไป|She applied for the role and enrolled in a training course.|attend in the meeting แก้อย่างไร?|attend the meeting หรือ participate in the meeting
21|25–26|hear / listen • ride / drive|ได้ยิน hear • ตั้งใจฟัง listen to; ควบคุมรถ drive|hear → ได้ยิน;listen to → ฟัง;ride → ขี่ / โดยสาร;drive → ขับ;take → โดยสารพาหนะ|I heard the announcement while riding the bus.|listen the announcement แก้อย่างไร?|listen to the announcement; hear รับกรรมได้ตรง ๆ
21|29–32|ขึ้น–ลง และคำงานบุคคล|rise ขึ้นเอง • raise ยกสิ่งอื่น|rise/increase/grow → เพิ่ม;raise → ยก / เพิ่มสิ่งหนึ่ง;decline/decrease/fall/drop → ลด;hire/recruit → รับคน;appoint/promote → แต่งตั้ง/เลื่อนตำแหน่ง;resign/retire → ลาออก/เกษียณ;dismiss/lay off → ให้ออก|The firm raised salaries as revenue rose.|rose salaries แก้อย่างไร?|raised salaries เพราะมีกรรม; revenue rose เป็นการเพิ่มขึ้นของรายได้เอง
21|33–40|พูด / แจ้ง / เสนอ|say เนื้อหา • tell คน • speak ภาษา • answer ตรง|say → that-clause;tell → คน + that-clause;speak → ภาษา / to-with คน;talk → about เรื่อง;notify/inform → คน + of เรื่อง;reply/respond → to;answer → คำถาม;advise → คน + to V1;suggest/recommend → V-ing / that-clause|Please inform customers of the change and respond to their questions.|reply the email แก้อย่างไร?|reply to the email หรือ answer the email; suggest someone to do ไม่ใช่โครงสร้างมาตรฐานนี้
21|41–51|Adv. เลือกตามสิ่งที่ขยาย|บ่อยขยายการทำ • มากขยาย Adj. • ประมาณขยายเลข|usually/often/regularly → ความถี่;carefully/clearly/promptly → วิธีทำ;very/highly/extremely → ระดับ;nearly/almost/approximately → จำนวนหรือความใกล้;sharply/dramatically/slightly → ขึ้นลง|Sales rose sharply, reaching approximately two million dollars.|sharply กับ approximately ขยายอะไร?|sharply ขยาย rose; approximately ขยายจำนวน two million ไม่ใช่เลือก Adv. จากตำแหน่งอย่างเดียว
22|1–9|Part 1: ภาพรวมก่อนรายละเอียด|ใคร → ทำอะไร → อยู่ตรงไหน → สิ่งของสภาพไหน|people → จำนวน / ท่าทาง;action → กริยา;position → Prep.;state → เต็ม/ว่าง เปิด/ปิด|Some boxes are stacked beside a doorway.|ภาพมีรถจอด แต่ช้อยซ์ is being repaired ต้องระวังอะไร?|being repaired บอกกำลังถูกซ่อม ต้องมีหลักฐานกิจกรรม; รถจอดเฉย ๆ ไม่พอ
22|3–9|doing / being done ในภาพ|ทำเอง ing • กำลังถูกทำ being V3|is/are + ing → กำลังทำ;is/are being + V3 → กำลังถูกทำ;is/are + V3 → สภาพ / ถูกทำ|A technician is repairing the printer. The printer is being repaired.|being repaired กับ repaired ต่างอย่างไร?|being repaired เน้นกำลังมีการซ่อม; repaired อาจบอกสภาพหรือ passive ตามบริบท
22|10–15|เสียงคล้าย ความหมายต่าง|ฟังทั้งพยางค์ และยืนยันกับภาพ|train → plane;thinking → drinking;package → baggage;coat → boat;right → write;pane → pain;ate → eight;read ปัจจุบัน → read อดีต|The worker is carrying a package.|ได้ยินคำคล้ายภาพแล้วเลือกเลยได้ไหม?|ไม่ได้ ต้องตรวจประธาน การกระทำ และตำแหน่งทั้งหมด; เสียงคล้ายเป็น distractor ได้
23|1–5|Part 2: ตั้งชนิดคำตอบ|who คน • where ที่ • when เวลา • why เหตุผล|who → บุคคล / ฝ่ายงาน;where → สถานที่;when → เวลา;why → เหตุผล;how often → ความถี่;how much → ราคา/ปริมาณ|When will the repair be completed? — Early next week.|คำตอบต้องทวนคำในคำถามไหม?|ไม่ต้อง; จับความหมายของคำถาม คำซ้ำหรือเสียงคล้ายอาจเป็นตัวลวง
23|1–7|คำขอและคำตอบอ้อม|ตอบเจตนา ไม่ต้องเริ่ม Yes/No ทุกครั้ง|Could you...? → คำขอ;Do you mind...? → No = ไม่รังเกียจ;Do you know where...? → ตอบตำแหน่งได้;statement → ช่วย / เสนอ / ตอบรับ|Could you send the file? — I'll do it after lunch.|I'll do it after lunch ใช้ตอบคำขอได้ไหม?|ได้ รับคำขอและบอกเวลา; ความสุภาพเป็นเพียงเบาะแส ต้องตรงเรื่องก่อน
23|8–12|Tag / ทางเลือก / คำถามปฏิเสธ|ตอบสถานการณ์จริง อย่ายึดรูป Yes/No อย่างเดียว|A or B? → เลือกหรือให้ทางเลือก;isn't/hasn't...? → ฟังความจริง;tag question → ยืนยัน;คำตอบอ้อม → มีความสัมพันธ์กับคำถาม|Would you prefer Monday or Tuesday? — Either works for me.|Either works หมายถึงอะไร?|วันไหนก็ได้ในสองตัวเลือก; ไม่ได้แปลว่าปฏิเสธทั้งสอง
24|3–11|Part 3: อ่านสามคำถามเป็นแผนฟัง|สถานการณ์ → ปัญหา → สิ่งที่จะทำต่อ|ก่อนฟัง → อ่านคำถาม / คนที่ถามถึง;ระหว่างฟัง → ใคร + ปัญหา + การแก้;ก่อนชุดใหม่ → ย้ายโฟกัสเมื่อจบ|The order is late. The woman offers to contact the warehouse.|ถ้าถาม What will the woman do next? ต้องฟังอะไร?|การกระทำที่ผู้หญิงเสนอหรือรับปาก ไม่ใช่ปัญหาของผู้ชายอย่างเดียว
24|12–18|สามเสียง + ภาพ + เจตนาคำพูด|จับชื่อกับเสียง • ข้อมูลเสียงต่อกับภาพ|three speakers → ใครพูด / ถูกกล่าวถึง;graphic → คอลัมน์ / ราคา / เวลา;quoted phrase → เจตนาในสถานการณ์;changed plan → ใช้ข้อมูลล่าสุด|The larger monitor is on sale; its price is listed in the chart.|ถามราคาโดยมีตาราง ต้องทำอย่างไร?|ฟังเงื่อนไขว่ารุ่นใด แล้วอ่านแถวที่ตรงกัน; อย่าเลือกจากเลขที่ได้ยินอย่างเดียว
25|1–4|Part 4: ผู้พูดคนเดียวมีเป้าหมาย|ใครพูด → ที่ไหน → เพื่ออะไร → ให้เราทำอะไร|voicemail → เหตุผลที่โทร / ขอให้ทำ;weather → สถานที่ / เวลา / คำแนะนำ;announcement → การเปลี่ยนแปลง;advertisement → ประโยชน์ / วิธีติดต่อ|Please leave your number; we will call you back tomorrow.|call back หมายถึงอะไร?|โทรกลับ; ฟังว่าผู้ฟังต้องฝากข้อมูลอะไร และผู้พูดจะทำอะไรต่อ
25|5–11|Short Talk + ตาราง|ดูแกนตาราง แล้วฟังการเปลี่ยนแปลง|graphic → อ่านหัวตาราง;switch/delay/change → ปรับจากตารางเดิม;final/next/after → ลำดับ|The last two presentations will switch times.|ตารางเดิมเพียงอย่างเดียวพอไหม?|ไม่พอ ถ้าเสียงบอกสลับเวลา ต้องนำเงื่อนไขใหม่ไปจับกับข้อมูลตาราง
26|1–6|Part 5: โครงสร้าง → รูป → ความหมาย|สแกนช้อยซ์เป็นประเภทโจทย์ ก่อนลงรายละเอียด|word family → หา POS.;verb forms → S. / tense / voice;different words → meaning / collocation;connector → หลังช่องว่าง + ความสัมพันธ์|The revised procedure was _____ approved. (formal / formally)|ต้องการอะไร และขยายอะไร?|formally เป็น Adv. ขยาย approved; ประธานและ passive ครบแล้ว
27|1–5|Part 6: อ่านภาพรวมก่อนเติม|เอกสารเรื่องอะไร ใครส่ง ให้ใคร ทำไม|grammar blank → ประโยคที่มีช่องว่าง;connector/vocab → ก่อน–หลัง;sentence insertion → ทั้งย่อหน้า / referent;tense → ลำดับเหตุการณ์ในเอกสาร|The notice announces a closure and then explains an alternative route.|ถ้าเลือกประโยคเกี่ยวกับ refund ในประกาศปิดทาง จะเช็กอะไร?|เช็กหัวเรื่อง จุดประสงค์ และประโยคก่อน–หลัง; ถูกไวยากรณ์ยังไม่พอ
27|5–15|ประโยคหาย: เชื่อมสองฝั่ง|this/these/it ต้องมีสิ่งอ้างถึง • therefore ต้องมีเหตุ|ก่อนช่อง → ตั้งหัวข้อ / เหตุ;ประโยคเติม → ต่อและอ้างถึง;หลังช่อง → ผล / รายละเอียด;น้ำเสียง → ผู้ส่ง / ผู้อ่าน|A new shuttle will run from Monday. This service will be free.|This service ต้องตามหลังอะไร?|ข้อมูลที่แนะนำบริการไว้แล้ว; ตรวจความต่อเนื่องทั้งสองฝั่ง ไม่ใช่แค่มีคำซ้ำ
28|1–6|Part 7: คำถาม → พิกัด → หลักฐาน|รู้ว่าถามอะไร แล้วอ่านจุดนั้นให้ละเอียด|purpose → จุดประสงค์;detail → พิกัดข้อมูล;NOT → เช็กทุกตัวเลือก;inference → อนุมานเท่าหลักฐาน;word meaning → บริบทในย่อหน้า|The notice asks tenants to move vehicles before maintenance.|ถาม purpose ต้องตอบรายละเอียดเวลาหรือเจตนา?|เจตนาที่ประกาศต้องการแจ้งหรือขอ; เวลาเป็นเพียงรายละเอียดสนับสนุน
28|2–9|สอง/สามเอกสาร: เชื่อมเรื่องก่อนเลข|เอกสาร A ใครเสนอ • B ใครตอบ • C ยืนยันอะไร|skim → ประเภท / ชื่อ / วันที่;link → คน / order / เหตุการณ์เดียวกัน;cross-reference → หลักฐานสองฝั่ง;latest → เงื่อนไขล่าสุด|A quote offers delivery on Friday; an email changes it to Monday.|ตอบวันส่งจาก quote อย่างเดียวได้ไหม?|ไม่ได้ถ้า email เปลี่ยนวันแล้ว; ต้องใช้ข้อมูลล่าสุดที่เกี่ยวข้อง
28|7–9|Paraphrase หาใจความเดียวกัน|charge↔fee • cancel↔call off • reserve↔book|reschedule → postpone / change the time;clients → customers;attire → clothing;inexpensive → affordable;long-lasting → durable;express appreciation → thank;50% off → half price|Customers may book a room at a discounted rate.|reserve ในคำถามอาจเจออะไรในบทความ?|book; และต้องตรวจเงื่อนไขราคา/วัน ไม่ใช่จับ synonym อย่างเดียว
28|9–12|Chat + เติมประโยค|ตามชื่อ เวลา และสิ่งที่ประโยคสั้นตอบกลับ|speaker → ใคร;time → ลำดับ;it/that → referent;quoted message → เจตนาจากก่อน–หลัง|Mina: The invoice has the old address. Leo: I'll fix that.|that หมายถึงอะไร?|ปัญหาที่อยู่เก่าใน invoice; ไม่ใช่แก้ทุกอย่างในโครงการ
29|1–89|จำลองสอบ: ความแม่นพร้อมเวลา|ตอบครบ • จัดเวลา • กลับมาซ่อมข้อเดา|Reading → 75 นาที;Part 5 → 30 ข้อ;Part 6 → 16 ข้อ;Part 7 → 54 ข้อ;ทบทวน → ผิด / เดา / ช้า|Mark an uncertain answer, continue, then review its pattern afterward.|ทำถูกเพราะจำข้อเดิม วัดความพร้อมพอไหม?|ยังไม่พอ ต้องทำข้อใหม่ที่วัด pattern เดียวกัน และดูเวลา/ความมั่นใจร่วมด้วย
30|1–2|โน้ตส่วนตัว: มองแกนก่อนช้อยซ์|S+V ครบไหม • ช่องนี้รับอะไร • ความหมายไปทางไหน|no → N.;never → V.;whose → N.;despite/in spite of → N./V-ing;unless → if not;yet → แต่ / ยัง ขึ้นกับหน้าที่;provided that → เงื่อนไข|Despite the delay, the shipment arrived before the deadline.|despite + S+V ใช้ได้ตรง ๆ ไหม?|ไม่ได้ในโครงสร้างนี้; ใช้ despite + N./V-ing หรือ despite the fact that + S+V
`.trim().split('\n').map((row,index): CourseCard => {
  const [chapter,pages,title,memory,patterns,example,prompt,answer]=row.split('|')
  return {id:`course-${chapter}-${index}`,chapter:Number(chapter),pages,title,memory,patterns:patterns.split(';'),example,prompt,answer}
})

// Each chunk can be recalled on its own; these are word facts, not copied worksheets.
const chunks: [number,string,string][] = [
  [1,'be engaged in','มีส่วนร่วม / ยุ่งอยู่กับ'],[1,'be involved in','มีส่วนเกี่ยวข้อง'],[1,'be interested in','สนใจ'],[1,'believe in','เชื่อใน'],[1,'participate in','มีส่วนร่วม'],[1,'result in','ส่งผลให้'],[1,'specialize in','เชี่ยวชาญ'],[1,'succeed in','ประสบความสำเร็จใน'],
  [2,'agree on','ตกลงกันเรื่อง'],[2,'be based on','มีพื้นฐานจาก'],[2,'concentrate on','ตั้งใจจดจ่อ'],[2,'focus on','มุ่งเน้น'],[2,'count on','พึ่งพา'],[2,'depend on','ขึ้นอยู่กับ / พึ่งพา'],[2,'rely on','พึ่งพา'],[2,'plan on','วางแผนว่าจะ'],[2,'spend on','ใช้เงินกับ'],[2,'arrive at','มาถึงจุดหรือสถานที่เฉพาะ'],[2,'be angry at','โกรธเรื่องหรือบุคคล'],[2,'be annoyed at','รำคาญ'],[2,'look at','มอง'],[2,'stare at','จ้อง'],
  [4,'add to','เพิ่มให้กับ'],[4,'get accustomed to','เริ่มคุ้นเคย'],[4,'get used to','เริ่มคุ้นเคย'],[4,'be dedicated to','อุทิศให้'],[4,'be devoted to','ทุ่มเทให้'],[4,'be exposed to','สัมผัส / เผชิญ'],[4,'limit to','จำกัดไว้ที่'],[4,'connect to','เชื่อมต่อกับ'],[4,'be opposed to','คัดค้าน'],[4,'object to','คัดค้าน'],[4,'look forward to','ตั้งตารอ'],
  [6,'agree with','เห็นด้วยกับ'],[6,'get acquainted with','เริ่มรู้จัก'],[6,'be familiar with','คุ้นเคยกับ'],[6,'be equipped with','มีอุปกรณ์'],[6,'be faced with','เผชิญกับ'],[6,'be pleased with','พอใจกับ'],[6,'be happy with','พอใจกับ'],[6,'be satisfied with','พึงพอใจกับ'],[6,'compete with','แข่งขันกับ'],[6,'deal with','จัดการกับ'],[6,'speak with','พูดกับ'],[6,'discuss something with','หารือเรื่องหนึ่งกับคน'],
  [8,'be anxious about','กังวลเรื่อง'],[8,'be concerned about','กังวลเรื่อง'],[8,'worry about','กังวลเรื่อง'],[8,'be excited about','ตื่นเต้นเรื่อง'],[8,'complain about','ร้องเรียนเรื่อง'],
  [9,'account for','คิดเป็นสัดส่วน / อธิบายเหตุ'],[9,'apologize for','ขอโทษเรื่อง'],[9,'apply for','สมัครหรือขอ'],[9,'consider someone for','พิจารณาคนสำหรับตำแหน่ง'],[9,'be prepared for','เตรียมพร้อมรับ'],[9,'search for','ค้นหา'],[9,'wait for','รอ'],[9,'be responsible for','รับผิดชอบ'],[9,'be famous for','มีชื่อเสียงเรื่อง'],[9,'be thankful for','ขอบคุณสำหรับ'],[9,'be grateful for','รู้สึกขอบคุณสำหรับ'],[9,'thank someone for','ขอบคุณคนสำหรับเรื่อง'],[9,'stand for','ย่อมาจาก / หมายถึง'],
  [10,'be composed of','ประกอบด้วย'],[10,'consist of','ประกอบด้วย'],[10,'be scared of','กลัว'],[10,'be terrified of','กลัวมาก'],[10,'be afraid of','กลัว'],[10,'be made of','ทำจากวัสดุที่ยังเห็นลักษณะเดิม'],[10,'approve of','เห็นชอบ'],[10,'get rid of','กำจัด'],[10,'take advantage of','ใช้ประโยชน์จาก'],[10,'take care of','ดูแล'],[10,'be proud of','ภูมิใจ'],
  [11,'benefit from','ได้ประโยชน์จาก'],[11,'borrow from','ยืมจาก'],[11,'differ from','ต่างจาก'],[11,'escape from','หนีจาก'],[11,'suffer from','ประสบหรือป่วยด้วย'],
]

export const courseCards: CourseCard[] = [...cards,...chunks.map(([page,word,meaning],index)=>({
  id:`chunk-${index}`,chapter:13,pages:String(page),title:word,memory:`จำเป็นคู่: ${word}`,patterns:[`${word} → ${meaning}`],example:'',
  prompt:`${word.slice(0,word.lastIndexOf(' '))} _____ : คำต่อที่ต้องจำคืออะไร?`,answer:`${word} — ${meaning}`,
}))]

const extra = `
21|1–3|V. ธุรกิจ: แยกสิ่งที่ทำให้ชัด|รับรอง • อนุมัติ • ทำสำเร็จ • ทำให้เสร็จ|endorse → รับรอง / สนับสนุน;approve → อนุมัติ;accomplish → ทำเป้าหมายสำเร็จ;finalize → จัดรายละเอียดให้เสร็จ;exceed/surpass → เกิน / เหนือกว่า;expand/widen → ขยาย;devise → คิดวิธีหรือแผน;invent/create → ประดิษฐ์ / สร้าง;deceive/mislead → หลอก / ทำให้เข้าใจผิด|The director approved the budget, and the team finalized the schedule.|approve และ finalize ต่างอย่างไร?|approve ตัดสินอนุมัติ; finalize ทำรายละเอียดขั้นสุดท้ายให้เสร็จ ต้องดูกรรมและสถานการณ์ ไม่ใช่จำว่าเป็น V. เหมือนกันแล้วใช้แทนกัน
11|1–5|12 Tenses: โครงสร้างครบชุด|เวลาคือ present/past/future • รูปคือ simple/continuous/perfect/perfect continuous|Present Simple → V1/V-s;Present Continuous → am/is/are + V-ing;Present Perfect → have/has + V3;Present Perfect Continuous → have/has been + V-ing;Past Simple → V2;Past Continuous → was/were + V-ing;Past Perfect → had + V3;Past Perfect Continuous → had been + V-ing;Future Simple → will + V1;Future Continuous → will be + V-ing;Future Perfect → will have + V3;Future Perfect Continuous → will have been + V-ing|By next June, Mina will have been working here for five years.|will have been working ให้ภาพเหตุการณ์อย่างไร?|มองจากจุดหนึ่งในอนาคต ย้อนว่าทำงานต่อเนื่องมานานเท่าไร; อย่าเลือก tense จาก keyword ตัวเดียวโดยไม่ดูเวลาและความสัมพันธ์
2|3|the กับชื่อเฉพาะ|ชื่อเฉพาะบางกลุ่มใช้ the; ชื่อเมืองและประเทศส่วนใหญ่มักไม่ใช้|the United States → ชื่อประเทศบางรูป;the Pacific Ocean → มหาสมุทร;the Thames → แม่น้ำ;Bangkok/Thailand → โดยทั่วไปไม่มี the|The supplier has offices in Thailand and the United States.|ชื่อประเทศทุกชื่อต้องมี the ไหม?|ไม่ต้อง; จำรูปชื่อเป็นชุด เช่น the United Kingdom แต่ Japan ไม่ใช้ the
3|1–2|Linking V. vs Action V.|มองว่าบอกสภาพหรือทำกิจกรรม|look tired → บอกสภาพ ใช้ Adj.;look carefully → วิธีมอง ใช้ Adv.;taste good → รสชาติดี;taste carefully → ชิมอย่างระวัง|The technician looked careful. The technician looked carefully at the screen.|ทำไม look ตามได้ทั้ง Adj. และ Adv.?|เพราะหน้าที่ของ look ต่างกัน; บอกสภาพประธานใช้ Adj. แต่วิธีทำการมองใช้ Adv.
7|1–2|กลุ่มคำ V. ที่ควรคุ้นตา|จำเป็นตระกูล ไม่ถือว่าท้ายทุกคำเป็น suffix|submit/commit → mit;support/report → port;compose/propose → pose;approve/improve → prove;respect/expect → pect;consist/persist → sist;receive/perceive → ceive|We expect the supplier to submit a revised proposal.|proposal และ propose เป็นชนิดใด?|proposal เป็น N.; propose เป็น V. การเห็นกลุ่มตัวสะกดช่วยจำ แต่ตำแหน่งตัดสินหน้าที่
11|11–12|ความถี่เรียงจากมากไปน้อย|เสมอ → มัก → บ่อย → บางครั้ง → แทบไม่ → ไม่เคย|always → เสมอ;usually/often → มัก / บ่อย;sometimes/occasionally → บางครั้ง;rarely/seldom/hardly/scarcely → แทบไม่;never → ไม่เคย|The team usually arrives early but is sometimes late.|is usually late กับ usually is late ควรจำแบบไหน?|ตำแหน่งทั่วไป Adv. ความถี่อยู่หลัง be และก่อน V. หลัก เช่น usually arrives
12|1–3|as / like • between / among|บทบาท as • คล้าย like; คู่ที่จำแนกได้ between • กลุ่ม among|as → บทบาท / ใช้เป็น;like → คล้าย;between → ความสัมพันธ์ระหว่างสิ่งที่แยกชัด;among → ท่ามกลางกลุ่ม|As a coordinator, Mina distributes tasks among the team members.|between ใช้ได้แค่สองเสมอไหม?|ไม่เสมอ: ใช้กับหลายฝ่ายที่แยกชัดได้; among เน้นอยู่ในกลุ่ม อย่าตัดสินจากจำนวนอย่างเดียว
12|3–6,8–15|on: สื่อ / วัน / การเดินทาง|วันบน on • สื่อบน on • ช่วงเดินทาง on|on → Monday / the screen / TV / the phone;on → a trip / a journey / business / vacation;in → a car / a taxi;on → a bus / a train / a plane|She answered the phone while on a business trip.|in a taxi แต่ on a train เพราะอะไร?|เป็นรูปใช้มาตรฐานที่ควรจำเป็นกลุ่ม; by taxi/train คือวิธีเดินทาง ไม่ระบุว่าอยู่บนคันหนึ่ง
12|10–15|in / at / on / out: ชุดสำนวนเพิ่ม|มุมมอง in • จุดบน at • ทันสมัย up to|in → my opinion / general / the advertisement;at → the top / the moment / present;on → the whole / the market;out of date → ล้าสมัย;up to date → ทันสมัย;by the way → ว่าแต่;on the way → ระหว่างทาง|The catalogue is out of date; please use the up-to-date list.|by the way กับ on the way แทนกันได้ไหม?|ไม่ได้ by the way ใช้เปลี่ยนหรือเพิ่มประเด็น; on the way กล่าวถึงระหว่างทาง
17|3–4,7–9|V. ที่รับได้สองรูป: ความหมายอาจต่าง|stop / remember / forget ต้องอ่านว่าเหตุการณ์ไหนก่อน|remember doing → จำเหตุการณ์ที่ทำแล้ว;remember to do → ไม่ลืมทำสิ่งที่ต้องทำ;try doing → ลองวิธีหนึ่ง;try to do → พยายามทำ;continue/like/prefer → รับสองรูปได้ตามบริบท|Remember to attach the file before sending the message.|remember attaching ต่างอย่างไร?|จำได้ว่าแนบไฟล์ไปแล้ว; remember to attach คืออย่าลืมแนบ ยังเป็นสิ่งที่ต้องทำ
18|5–8|a/an และ the ไม่ได้เลือกขั้นให้เสมอ|ดูความหมายการเทียบจริง ก่อนใช้ keyword เป็นคำใบ้|a → อาจตามด้วย comparative เช่น a better plan;the → อาจตามด้วย Adj. ปกติ เช่น the new office;of all → ช่วยบอกการเทียบทั้งกลุ่ม;one of the → superlative + plural N. ในโครงสร้างนี้|This is a better plan. It is the best of all three.|เห็น the แล้วตอบขั้นสูงสุดทันทีได้ไหม?|ไม่ได้ the new plan ใช้ Adj. ปกติ; ต้องมีความหมายเทียบที่สุดของกลุ่มด้วย
19|6–11|Connector เป็นกลุ่มความหมาย|เพิ่ม • ผล • ขัด • ตรงข้าม • ยกตัวอย่าง • พูดใหม่|owing to/due to/on account of → เพราะ;regarding/concerning → เกี่ยวกับ;regardless of → โดยไม่คำนึงถึง;according to → ตามแหล่งข้อมูล;in addition to → นอกจาก;in contrast/on the other hand → ตรงข้าม;similarly → เช่นเดียวกัน;in other words → กล่าวอีกแบบ|According to the memo, the deadline has been extended.|according to ต้องตามด้วยอะไรในตัวอย่างนี้?|แหล่งข้อมูล the memo เป็นกลุ่มนาม ไม่ใช่ S+V โดยตรง
21|4–8|N. เกี่ยวกับสินค้าและการเดินทาง|จำชื่อสิ่งให้จับคู่กับ V. ได้|priority → ลำดับสำคัญ;satisfaction → ความพึงพอใจ;effectiveness → การได้ผล;attention → ความใส่ใจ;itinerary → แผนเดินทาง;excursion → ทริปสั้น;reservation → การจอง;appointment → นัดหมาย;circumstances → สถานการณ์;indication → สิ่งบ่งชี้|The itinerary includes a short excursion before the appointment.|itinerary กับ excursion ต่างอย่างไร?|itinerary คือแผนหรือกำหนดการ; excursion คือการเดินทางท่องเที่ยวช่วงสั้น
21|7–9|Shopping เป็นลำดับการทำ|เปรียบเทียบ → เลือก → ลอง → ซื้อ → ส่ง|compare → เทียบ;select/pick → เลือก;try on → ลองสวม;bargain → ต่อรอง;purchase/buy → ซื้อ;checkout → จุดหรือขั้นตอนชำระ;pack → บรรจุ;ship out → ส่งออก;deliver → ส่งถึง;unbox → แกะกล่อง|Compare the prices before selecting a product.|try กับ try on ใช้แทนกันได้ทุกอย่างไหม?|ไม่ได้ try on ใช้ลองสวม เช่น เสื้อ; try the software คือทดลองใช้ ไม่ใช้ on
21|8–10|ศัพท์การเงินใน Sales|ซื้อแล้วได้ receipt • เป็นหนี้ debt • ลงทุน invest|supply → อุปทาน / จัดหา;demand → อุปสงค์ / ความต้องการ;profit → กำไร;debt → หนี้;contract → สัญญา;transaction → ธุรกรรม;subscription → การสมัครรับบริการ|Demand increased, but the supplier could not expand supply.|receipt กับ invoice ต่างอย่างไร?|receipt ยืนยันการชำระเงิน; invoice แจ้งรายการและยอดเรียกเก็บ ไม่ได้ยืนยันว่าจ่ายแล้วเสมอไป
21|11–13|จำเป็น vs เป็นไปได้|required ไม่ใช่ likely • necessary ไม่ใช่ possible|essential/necessary/important → สำคัญหรือจำเป็น;mandatory/compulsory → บังคับ;imperative/vital/crucial → สำคัญมาก;possible/probable/likely → เป็นไปได้;impossible/unlikely → เป็นไปไม่ได้หรือโอกาสน้อย|It is essential that every visitor wear a badge.|wear ทำไมไม่เติม s หลัง every visitor ในประโยคนี้?|เป็น mandative subjunctive หลัง essential that ในตัวอย่างนี้ ใช้ V. ไม่ผัน; ไม่ใช่ทุก that-clause ใช้ V1
21|14–16|แนวโน้ม N. + Adj. / V. + Adv.|นามใช้คุณศัพท์ • กริยาใช้วิเศษณ์|a sharp/significant/dramatic → increase/decrease;a steady/gradual → increase/decrease;a slight/modest → increase/decrease;rise sharply/steadily/slightly → V. + Adv.|There was a gradual increase; sales increased gradually.|a gradually increase ถูกไหม?|ไม่ถูก increase ในกลุ่มนี้เป็น N. ใช้ a gradual increase
21|16|กลุ่ม ble: ความสามารถกับความพร้อม|capable of • available for • suitable for • responsible for|reliable → ไว้ใจได้;accessible → เข้าถึงได้;available → พร้อมให้ใช้;affordable → จ่ายไหว;capable of → สามารถทำ;suitable for → เหมาะกับ;responsible for → รับผิดชอบ|The software is accessible to all staff and suitable for beginners.|capable to managing แก้อย่างไร?|capable of managing; แต่ able to manage เป็นอีกโครงสร้าง
21|17–18|ive: คำที่ไม่ควรเหมารวม|รูปเหมือนกันแต่จุดใช้งานต่างกัน|informative → ให้ข้อมูล;lucrative → ทำกำไร;excessive → มากเกิน;extensive → ครอบคลุม;intensive → เข้มข้น;repetitive → ซ้ำ;supportive → สนับสนุน;appreciative → รู้สึกขอบคุณ;alternative → ทางเลือก;initiative → ความริเริ่ม / โครงการ (N.)|The intensive course includes extensive practice.|intensive กับ extensive ต่างอย่างไร?|intensive เน้นความเข้มข้น; extensive เน้นขอบเขตกว้างหรือปริมาณมาก
21|19–23|ศัพท์สถานะ ed ในงาน|ได้รับอนุญาต • ถูกจัดตาราง • ติดตั้งแล้ว • มีจำกัด|permitted/authorized → ได้รับอนุญาต;rewarded → ได้รับรางวัล;scheduled → ถูกจัดเวลา;installed → ติดตั้ง;occupied → มีผู้ใช้อยู่;limited → จำกัด;updated → ปรับให้ใหม่;expected → คาดว่าจะ|The installation is scheduled for Friday, but access is limited.|occupied กับ available หมายถึงสภาพเดียวกันไหม?|ไม่เหมือน occupied ถูกใช้อยู่; available ว่างหรือมีให้ใช้ ต้องเช็กบริบท
21|30–32|เส้นทางงานบุคคล|สมัคร → ส่งเอกสาร → สัมภาษณ์ → รับ → เลื่อน → ออก|seek/recruit → มองหา / รับคน;submit → ส่งเอกสาร;interview → สัมภาษณ์;hire/employ → จ้าง;appoint → แต่งตั้ง;promote → เลื่อน;demote → ลดตำแหน่ง;terminate/dismiss → เลิกจ้าง;lay off → ให้ออกเพราะลดคน;resign → ลาออกเอง|The firm is recruiting analysts and will interview applicants next week.|resign กับ dismiss ต่างอย่างไร?|resign ลูกจ้างลาออกเอง; dismiss นายจ้างให้ออก
21|33–40|แนะ / ขอ / แจ้ง: เลือกโครงสร้าง|recommend สิ่งหรือวิธี • introduce คน • advise คนให้ทำ|recommend → N./V-ing;introduce → คน + to คน;advise/encourage/invite/allow → คน + to V1;suggest/propose/request/demand/require → that-clause;inform/notify/remind → คน + of/about เรื่อง|Mina introduced the consultant to us and advised us to review the plan.|introduce กับ recommend ใช้แทนกันได้ไหม?|ไม่ได้ introduce คือทำให้รู้จัก; recommend เสนอว่าสิ่งหรือวิธีใดเหมาะ
21|25–26|ทักทายแบบ How|ถามสารทุกข์ ไม่จำเป็นต้องตอบกิจกรรม|How are you? → สบายดีไหม;How are you doing? → เป็นอย่างไรบ้าง;How is everything? → ทุกอย่างเป็นอย่างไร|How are you doing? — Quite well, thanks.|I'm printing the report เป็นคำตอบดีที่สุดเสมอไหม?|ไม่เสมอ ถ้าเป็นคำทักทายต้องตอบความเป็นอยู่; ถ้า What are you doing? จึงถามกิจกรรม
21|44–51|Adv. ไม่ได้หมายถึงความถี่ทั้งหมด|เวลา • วิธี • ระดับ • ประมาณ • แนวโน้ม|currently/recently/originally → ตอนนี้/ช่วงนี้/เดิม;carefully/closely/clearly → อย่างระวัง/ใกล้ชิด/ชัด;promptly/immediately → โดยเร็ว/ทันที;fairly/relatively/slightly → ค่อนข้าง/เทียบแล้ว/เล็กน้อย;equally/efficiently/directly → เท่ากัน/มีประสิทธิภาพ/ตรง|The system was originally designed for smaller teams.|originally บอกความถี่หรือเวลา?|เวลา/สภาพเดิม ไม่ได้แปลว่าทำบ่อย; ต้องแปล Adv. เมื่อช้อยซ์เป็น Adv. เหมือนกัน
22|10–15|เสียงเดียวกันหลายความหมาย|อ่านหน้าที่ด้วย: N. สิ่ง • V. การทำ|left → ซ้าย / ออกไปแล้ว;glass/glasses → แก้ว / แว่น;close/clothes → ปิด / เสื้อผ้า;record → บันทึก N./V.;wave/ring → คลื่นหรือโบก / แหวนหรือเสียงโทร;rose → ดอกกุหลาบ / rise ช่อง 2;row → แถว / พาย|The receptionist recorded the message and kept a written record.|record เป็น N. หรือ V.?|เป็นได้ทั้งสอง: recorded เป็น V. ในประโยคแรก; a written record เป็น N. ต้องฟัง stress และบริบท
`.trim().split('\n').map((row,index):CourseCard=>{
  const [chapter,pages,title,memory,patterns,example,prompt,answer]=row.split('|')
  return {id:`extra-${chapter}-${index}`,chapter:Number(chapter),pages,title,memory,patterns:patterns.split(';'),example,prompt,answer}
})
courseCards.push(...extra)

export function courseSkills(chapter: number): SkillId[] {
  if (chapter === 26 || chapter === 29 || chapter === 30) return ['part-of-speech']
  return Object.entries(skillChapterIds).filter(([,ids])=>ids.includes(chapter)).map(([skill])=>skill as SkillId)
}

export function recallForQuestion(question: Question) {
  const terms=[...new Set(`${question.coaching?.memory??''} ${question.choices.find(c=>c.id===question.answer)?.text??''}`.toLowerCase().match(/[a-z]{3,}/g)??[])]
  const relevant=courseCards.filter(card=>courseSkills(card.chapter).some(skill=>question.skills.includes(skill)))
  const score=(card:CourseCard)=>terms.reduce((n,term)=>n+(new RegExp(`\\b${term}\\b`,'i').test(`${card.memory} ${card.patterns.join(' ')}`)?1:0),0)
  return relevant.sort((a,b)=>score(b)-score(a))[0]
}

export function cardIsDue(state: TrainerState, id: string, now = Date.now()) {
  const review=state.vocabReview[`card:${id}`]
  if (!review?.lastAt) return true
  const days=review.known > review.hard+2 ? 7 : review.known > review.hard ? 3 : 1
  return now-review.lastAt >= days*86_400_000
}
