// Reviewed tags are word positions in the completed sentence (punctuation excluded).
// POS and sentence function stay separate: a noun can modify another noun.
export const grammarClasses: Record<string, string> = {
  D:'Det.', PD:'Poss. Det.', PN:'Poss. N.', PR:'Pron.', N:'N.', A:'Adj.', AC:'Adj. ขั้นกว่า', AS:'Adj. ขั้นสูงสุด',
  ADV:'Adv.', ADVC:'Adv. ขั้นกว่า', V:'V.', V1:'V1', V2:'V2', V3:'V3', ING:'V-ing', G:'Gerund (N.)',
  BE:'V. be', BING:'V-ing (be)', AUX:'Aux.', MOD:'Modal', P:'Prep.', TO:'Inf. to', CJ:'Conj.', REL:'Relative pron.', CMP:'Comparison', NUM:'Number', TIME:'Time', INT:'Question word',
}
export const grammarFunctions: Record<string, [string, string]> = {
  S:['ประธานหลัก','main subject'], V:['กริยาหลัก','main verb'], AUX:['กริยาช่วย','auxiliary'], O:['กรรมหลัก','main object'],
  C:['เติมเต็มประธาน','subject complement'], OC:['เติมเต็มกรรม','object complement'], NM:['ขยายนาม','noun modifier'],
  MV:['ขยายกริยา','verb modifier'], MA:['ขยาย Adj.','adjective modifier'], MD:['ขยาย Adv.','adverb modifier'],
  PO:['กรรมของ Prep.','preposition object'], G:['gerund รับกรรมได้','gerund with verb function'],
  RS:['ประธานอนุประโยค','subordinate subject'], RV:['กริยาอนุประโยค','subordinate verb'], RO:['กรรมอนุประโยค','subordinate object'],
  RAUX:['กริยาช่วยอนุประโยค','subordinate auxiliary'],
  RC:['ขยายนามแบบลดรูป','reduced relative modifier'], CM:['เชื่อมเปรียบเทียบ','comparison marker'],
  CL:['เชื่อมอนุประโยค','subordinate connector'], TIME:['บอกเวลา','time expression'], POSS:['แสดงเจ้าของ','possession'],
  GP:['passive หลัง Prep.','passive gerund phrase'], ASK:['คำถาม','question focus'],
}

export const reviewedGrammar: Record<string, string> = {
  'cmp-1':'D PN:NM N:S BE:V ADV:MA AC:C CMP:CM V3:RV',
  'cmp-2':'D A:NM N:S BE:V ADV CMP:CM A:C CMP:CM D A:NM N:PO',
  'cmp-3':'P D NUM N:PO D A:S BE:V D ADV:MA A:C',
  'cmp-4':'D A:NM N:S BE:V ADV:MD ADV CMP:CM A:C CMP:CM D A:NM PR:PO',
  'cmp-5':'D A:NM N:S V:V ADV:MD ADV ADVC:MV CMP:CM D A:NM N:PO',
  'pos-1':'D N:S V2:V D N:O ADV:MV',
  'pos-2':'D A:NM N:S AUX:AUX V3:V N:NM N:O',
  'pos-3':'PR:S V2:V D A:NM N:O P D N:PO',
  'pos-4':'D N:S V2:V PD N:O P D A:NM N:PO',
  'pos-5':'D N:S BE:V ADV:MA A:C P D A:NM N:PO',
  'tense-1':'D N:NM N:S AUX:AUX V3:V NUM A:NM N:O P D N:PO P D N:PO',
  'tense-2':'P D N:PO D N:RS V2:RV D N:S AUX:AUX V3:V D N:NM N:O',
  'tense-3':'D N:S MOD:AUX V1:V PD A:NM N:NM N:O A:NM N:TIME',
  'tense-4':'N N:S BE:AUX ING:V D N:O CJ:CL D N:RS ADV:MV V2:RV P',
  'tense-5':'D N:S AUX:AUX ADV BE:AUX V3:V ADV CJ D N:NM N:RS MOD:RAUX V1:RV N:RO',
  'prep-1':'D N:S MOD:AUX BE:AUX V3:V P NUM TIME:TIME N:TIME',
  'prep-2':'N N:S BE:V A:C P G:G D N:O',
  'prep-3':'D A:NM N:S V:V P D A:NM N:PO',
  'prep-4':'ADV V1:V P D A:NM N:PO P A:NM N:PO',
  'prep-5':'D N:S MOD:AUX V1:V A:C P D A:NM N:PO',
  'conj-1':'D A:NM N:S MOD:AUX V1:V CJ:CL D N:RS V:RV A:C',
  'conj-2':'N N:S V2:V ADV:MV CJ CJ:CL PR:RS MOD:RAUX V1:RV D N:RO',
  'conj-3':'CJ:CL D N:RS BE:RV A:C D N:S MOD:AUX V1:V D ADV:MA A:NM N:O ADV:MV',
  'conj-4':'D N:S BE:AUX V3:V CJ:CL D N:RS AUX:RAUX V3:RV N:RO',
  'conj-5':'D N:S MOD:AUX V1:V A:C CJ:CL D N:RS V1:RV TO V1 PR:RO',
  'sva-1':'PR:S P D N:NM N:PO BE:AUX V3:V P D A:NM N:PO',
  'sva-2':'D N:S P D N:PO BE:V A:C',
  'sva-3':'D N:S P A:NM N:PO AUX:AUX V3:V D N:TIME',
  'sva-4':'CJ D N:S CJ D N:S BE:V A:C D N:TIME',
  'sva-5':'PR:S P D A:NM N:PO BE:V A:C P N:PO',
  'pass-1':'D N:S BE:AUX V3:V CJ:CL N:RS BE:RAUX V3:RV',
  'pass-2':'D N:S MOD:AUX BE:AUX V3:V CJ:CL PR:RS BE:RAUX V3:RV P N:PO',
  'pass-3':'D A:NM N:S AUX:AUX ADV BE:AUX V3:V P D N:PO',
  'pass-4':'D N:S MOD:AUX BE:AUX V3:V P D A:NM N:PO A:NM N:TIME',
  'pass-5':'D N:S BE:AUX BE:AUX V3:V CJ:CL D N:NM N:RS V2:RV',
  'rel-1':'D N:S REL:RS V2:RV D N:RO V2:V D N:O',
  'rel-2':'D N:S PD:POSS N:RS BE:RAUX V3:RV MOD:AUX V1:V A:C',
  'rel-3':'D N:S REL:RS V2:RV A:NM N:TIME BE:V ADV P A:NM N:PO',
  'rel-4':'D N:S REL:CL D N:RS BE:RAUX V3:RV AUX:AUX V3:V PD N:NM N:O',
  'rel-5':'D N:S P REL:PO PR:RS V2:RV V2:V D N:O',
  'pro-1':'N:S MOD:AUX V1:V PD:POSS N:NM N:O A:OC P D N:TIME',
  'pro-2':'N:S MOD:AUX V1:V PR:O P D A:NM N:PO',
  'pro-3':'D A:NM N:S BE:V ADV:MA A:C CMP:CM PR:PO V3:RC A:NM N:TIME',
  'pro-4':'D NUM N:S BE:V A:C CJ PR:RS BE:RV ADV:MA A:C TO V1',
  'pro-5':'D N:S V2:V PR:O REL:RS AUX:RAUX V3:RV P D N:PO',
  'col-1':'D N:S MOD:AUX V1:V D N:NM N:O A:NM N:TIME',
  'col-2':'ADV V1:V D N:O P N:PO P N:PO',
  'col-3':'D N:S V:V TO V1 D A:NM N:NM N:O P N:TIME',
  'col-4':'D N:S V2:V TO V1 D N:O CJ:CL AC:NM N:RS BE:RV A:C',
  'col-5':'D A:NM N:S BE:AUX V3:V TO V1 N:NM N:O',
  'coach-p5-1':'D A:NM N:NM N:S AUX:AUX V3:V D N:NM N:O ADV:MA A:OC P G:G N:O',
  'coach-p5-2':'P D A:NM N:PO D N:S V2:V D ADV:MA A:NM N:O P D A:NM N:PO',
  'coach-p5-3':'D N:NM N:S MOD:AUX ADV V1:V N:O P A:NM N:PO P D N:NM N:PO',
  'coach-p5-4':'N:S BE:AUX V3:V TO ADV:MV V1 D N:NM N:O CJ CJ:CL D N:RS MOD:RAUX V1:RV P N:PO',
  'coach-p5-5':'D N:S P D N:PO REL:RS V1:RV PD N:NM N:RO BE:AUX V3:V P D N:NM N:PO',
  'coach-p5-6':'CJ D A:NM N:S CJ D N:NM N:S BE:AUX V3:V TO V1 D N:NM N:O',
  'coach-p5-7':'P D N:PO D A:NM N:NM N:RS V:RV A:NM N:TIME D N:S MOD:AUX AUX:AUX V3:V D P PD A:NM N:NM N:O',
  'coach-p5-8':'CJ:CL D N:RS V2:RV ADV:TIME D N:NM N:S AUX:AUX BE:AUX ING:V D A:NM N:O P AC:NM CMP:CM NUM N:TIME',
  'coach-p5-9':'D N:S V3:RC P D N:PO MOD:AUX BE:AUX V3:V P D N:NM N:PO ADV:MV',
  'coach-p5-10':'D A:NM N:NM N:S MOD:AUX BE:AUX V3:V P D N:PO CJ:CL D A:NM N:NM N:RS V:RV',
  'coach-p5-11':'D N:NM N:S BE:V A:C P G:G N:NM N:O P D N:PO P N:NM N:PO',
  'coach-p5-12':'N:S BE:V A:C P N:PO ADV P G:G A:NM N:O P D A:NM N:PO',
  'coach-p5-13':'D N:S V:V N:NM N:O CJ:CL N:RS ING:RC P A:NM N:PO BE:RAUX V3:RV',
  'coach-p5-14':'CJ:CL D A:NM N:RS V2:RV D A:NM N:RO D A:NM N:S BE:AUX V3:V P D N:NM N:PO',
  'coach-p5-15':'D N:S PD:POSS N:RS V2:RV P A:NM N:NM N:PO AUX:AUX BE:AUX V3:V TO V1 P D A:NM N:PO',
  'coach-p5-16':'D A:NM N:S BE:V ADV:MA A:C CMP:CM PR:PO V3:RC P A:NM PN:NM PN:NM N:PO',
  'coach-p5-17':'D ADV:MA V3:NM N:NM N:S V:V ADV:MD ADV ADVC:MV CMP:CM D N:PO PR:RS V2:RV',
  'coach-p5-18':'P D D N:PO V3:RC D PR:S V3:RC P N N:PO BE:V P ADV D ADV:MA A:C',
  'coach-p5-19':'D N:S AUX:AUX V3:V TO V1 D A:NM N:NM N:O V3:RC P P PD N:NM N:PO',
  'coach-p5-20':'D N:S MOD:AUX V1:V P N:PO CJ:CL D N:RS V:RV NUM PN:NM A:NM N:RO P N:PO',
  'coach-p5-21':'TO V1 G:O N:O N:NM N:S MOD:AUX BE:AUX V3:V P P D AS:NM A:NM N:PO',
  'coach-p5-22':'N:S V3:RC P D N:NM N:PO MOD:AUX ADV BE:AUX V3:V ADV P D PN:NM N:PO',
  'coach-p5-23':'ADV V1:V D N:NM N:O P N:TIME CJ:CL D N:RS V:RV A:NM A:NM N:RO',
  'coach-p5-24':'D A:NM N:S P P D A:NM N:PO BE:V A:C P D N:NM N:NM N:PO',
  'coach-p6-101':'N:S BE:AUX V3:V TO V1 CJ:CL PD N:NM N:RS BE:RV A:C CJ:CL D N:RS V:RV',
  'coach-p6-102':'ADV D A:NM N:S MOD:AUX BE:AUX V3:V ADV:MV P N:TIME NUM',
  'coach-p6-103':'D N:S P G:G D N:NM N:O MOD:AUX BE:AUX V3:V P N:TIME NUM',
  'coach-p6-104':'PR:S MOD:AUX V1:V PD N:NM N:O P BING:AUX V3:GP P D N:PO',
  'coach-p6-105':'CJ:CL D N:RS P N:PO AUX:RAUX V3:RV PD A:NM N:RO D N:S AUX:AUX BE:AUX V3:V P N:PO NUM P D A:NM N:PO',
  'coach-p6-106':'ADV V1:V N:O TO V1 NUM N:TIME ADV:MV CJ CJ:CL N:RS MOD:RAUX BE:RAUX V3:RV P D A:NM N:PO',
  'coach-p6-107':'N:S P D N:PO MOD:AUX V1:V N:O P D A:NM N:PO',
  'coach-p6-108':'N:S REL:RS V:RV D A:NM N:RO MOD:AUX V1:V PD A:NM N:O CJ:CL D N:RS BE:RV A:C TO V1 A:NM N:NM N:RO',
  'coach-p7-201':'INT:ASK AUX:AUX N N:S V1:V D A:NM N:NM N:O',
  'coach-p7-202':'D N:S V:V D N:NM N:O TO BE:AUX V3',
  'coach-p7-203':'PR:ASK BE:V D A:NM N:S P N:PO N NUM',
  'coach-p7-204':'P D N:PO MOD:AUX N N:S V1:V D N:O',
  'coach-p7-205':'PR:S BE:AUX V3:V P D N:NM N:PO',
}
