import type { LessonDefinition, SkillId, WorkedExample } from './types'

const c = (a: string, b: string, c: string, d: string) => [
  { id: 'A', text: a }, { id: 'B', text: b }, { id: 'C', text: c }, { id: 'D', text: d },
]

const e = (
  id: string,
  skill: SkillId,
  stem: string,
  choices: [string, string, string, string],
  answer: string,
  clue: string,
  rule: string,
  explanation: string,
  trap: string,
  difficulty: 1 | 2 | 3 | 4 | 5 = 2,
): WorkedExample => ({ id, skill, stem, choices: c(...choices), answer, clue, rule, explanation, trap, difficulty })

export const lessons: LessonDefinition[] = [
  {
    skill: 'verb-tense',
    title: 'Verb Tense & Time Signals',
    shortTitle: 'Tense',
    icon: 'T',
    summary: 'Match the verb form to time markers, sequence, and completion—not to the closest verb-looking option.',
    strategy: ['Circle the time signal first.', 'Decide present / past / future.', 'Check simple vs continuous vs perfect.', 'Only then compare the choices.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('tense-1','verb-tense','The sales team _____ three new contracts since the beginning of this month.',['signs','signed','has signed','is signing'],'C','Signal: “since the beginning of this month.”','since + starting point → present perfect when the period continues to now.','The contracts were signed during a period that began in the past and is still connected to the present, so “has signed” fits.','“Signed” is tempting because the action happened in the past, but “since” makes the present connection important.',2),
      e('tense-2','verb-tense','By the time the director arrived, the staff _____ the presentation room.',['prepares','had prepared','has prepared','is preparing'],'B','Two past events: preparation happened first.','Earlier past action → past perfect; later past action → simple past.','“Had prepared” clearly places the preparation before “arrived.”','Simple past can sound possible in conversation, but TOEIC often tests the explicit earlier-past relationship.',3),
      e('tense-3','verb-tense','The company _____ its annual customer survey next Monday.',['launches','launched','will launch','has launched'],'C','Signal: “next Monday.”','A clear future time normally needs a future form unless the sentence describes a fixed schedule with present simple.','Here the company is announcing a future action, so “will launch” is the safest answer.','Present simple is tempting because schedules can use it, but this sentence describes a company action rather than a timetable entry.',1),
      e('tense-4','verb-tense','Ms. Alvarez _____ the supplier when the power suddenly went out.',['calls','was calling','has called','had called'],'B','One action was in progress when another interrupted it.','Background action in progress → past continuous; interrupting event → simple past.','“Was calling” shows the phone action was happening at the moment the power went out.','Past perfect would mean the call had already finished before the outage.',3),
      e('tense-5','verb-tense','The invoices _____ yet, so the accounting team cannot release payment.',['were not approved','have not been approved','are not approving','had not approve'],'B','Signal: “yet” + present result.','yet commonly pairs with present perfect; invoices receive the action, so use present perfect passive.','“Have not been approved” connects the unfinished approval to the present consequence.','Simple past focuses on a finished past time and does not fit “yet” as naturally here.',4),
    ],
  },
  {
    skill: 'part-of-speech',
    title: 'Word Form: Noun, Verb, Adjective, Adverb',
    shortTitle: 'Word Form',
    icon: 'W',
    summary: 'Use the grammar around the blank to determine the required word class before thinking about meaning.',
    strategy: ['Look left and right of the blank.', 'After an article, expect a noun or adjective+noun.', 'Before a noun, expect an adjective.', 'To modify a verb/adjective, expect an adverb.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('pos-1','part-of-speech','The technician completed the installation _____.',['success','successful','successfully','succeed'],'C','The blank describes how the technician “completed” something.','Verb + ___ → adverb when describing how the action is done.','“Successfully” is the adverb that modifies “completed.”','“Successful” is an adjective; it cannot directly modify the verb here.',1),
      e('pos-2','part-of-speech','The new policy has improved employee _____.',['productive','productivity','productively','produce'],'B','“Improved” needs a thing that was improved.','Verb + object → noun.','“Productivity” is the noun naming what improved.','“Productive” is an adjective and would need a noun after it.',2),
      e('pos-3','part-of-speech','We received a _____ response from the supplier.',['prompt','promptly','promptness','prompted'],'A','The blank comes directly before the noun “response.”','Before a noun → adjective.','“Prompt” is the adjective describing the response.','“Promptly” is an adverb and cannot directly describe a noun.',1),
      e('pos-4','part-of-speech','The board expressed its _____ with the revised plan.',['satisfy','satisfied','satisfaction','satisfactorily'],'C','Possessive “its” is followed by a noun.','Possessive adjective + noun.','“Satisfaction” is the required noun.','“Satisfied” is an adjective, and “satisfactorily” is an adverb.',2),
      e('pos-5','part-of-speech','The report was _____ different from the original estimate.',['surprise','surprised','surprising','surprisingly'],'D','The blank modifies the adjective “different.”','Adverb + adjective.','“Surprisingly” modifies “different.”','“Surprising” is an adjective and would describe a noun instead.',3),
    ],
  },
  {
    skill: 'preposition',
    title: 'Prepositions & Business Phrases',
    shortTitle: 'Prepositions',
    icon: 'P',
    summary: 'TOEIC frequently tests fixed business phrases and deadline/location relationships.',
    strategy: ['Check whether the blank belongs to a fixed phrase.', 'Learn verb + preposition as one chunk.', 'Use “by” for deadlines.', 'Use “during” with periods/events, not deadline points.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('prep-1','preposition','All applications must be received _____ 5:00 P.M. Friday.',['by','during','among','through'],'A','This is a deadline.','by + time = no later than that time.','“By 5:00 P.M.” means the application can arrive earlier, but not later.','“During” needs a period or event, such as “during the meeting.”',1),
      e('prep-2','preposition','Ms. Park is responsible _____ coordinating the workshop.',['to','for','with','at'],'B','Fixed phrase: responsible ___.','be responsible for + noun/gerund.','“Responsible for coordinating” is the standard collocation.','“Responsible to” usually identifies the person or authority you report to.',1),
      e('prep-3','preposition','The new procedure applies _____ all regional offices.',['at','to','for','with'],'B','Fixed phrase: apply ___.','apply to = affect or concern.','The procedure applies “to” the offices.','“Apply for” means request something, such as a job.',2),
      e('prep-4','preposition','Please refer _____ the attached chart for current prices.',['to','at','from','by'],'A','Fixed verb phrase.','refer to + document/person/topic.','“Refer to the chart” is the natural expression.','“Refer at” is not a standard pattern.',1),
      e('prep-5','preposition','The store will remain closed _____ the national holiday.',['during','between','beside','toward'],'A','The holiday is a period/event.','during + period/event.','“During the national holiday” correctly describes the period of closure.','“By” would mark a deadline instead.',2),
    ],
  },
  {
    skill: 'conjunction',
    title: 'Conjunctions & Logical Relationships',
    shortTitle: 'Connectors',
    icon: 'C',
    summary: 'Choose the connector only after identifying the relationship between the two ideas.',
    strategy: ['Reason? because/since.', 'Contrast? although/even though.', 'Condition? if/unless/provided that.', 'Purpose? so that/in order to.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('conj-1','conjunction','The outdoor ceremony will continue _____ the weather becomes unsafe.',['unless','because','although','so that'],'A','The second clause gives an exception condition.','unless = if not / except if.','The event continues except if the weather becomes unsafe.','“Although” would express contrast, not the condition that stops the event.',2),
      e('conj-2','conjunction','Ms. Lee arrived early _____ she could test the projector.',['so that','despite','whereas','unless'],'A','The second clause explains purpose.','so that + clause = purpose.','She arrived early for the purpose of testing the projector.','“Despite” is a preposition and cannot directly introduce this full clause.',2),
      e('conj-3','conjunction','_____ the budget is limited, the team will repair the most urgent equipment first.',['Since','Despite','Whereas','Until'],'A','The first clause explains the reason for the decision.','since/because + clause = reason.','Because the budget is limited, prioritizing urgent equipment makes sense.','“Despite” requires a noun phrase, e.g. “Despite the limited budget.”',2),
      e('conj-4','conjunction','The proposal was approved _____ several members had raised concerns.',['although','because','unless','so that'],'A','Approval happened in contrast to the concerns.','although/even though = contrast between clauses.','“Although” correctly connects two contrasting facts.','“Because” would say the concerns caused the approval, which is illogical.',2),
      e('conj-5','conjunction','The contract will remain valid _____ both parties agree to terminate it.',['until','because','whereas','therefore'],'A','The second clause marks the endpoint.','until + clause = continuing up to a time/event.','The contract stays valid up to the moment both parties terminate it.','“Therefore” is a conjunctive adverb and cannot fit this structure.',3),
    ],
  },
  {
    skill: 'subject-verb',
    title: 'Subject–Verb Agreement',
    shortTitle: 'Agreement',
    icon: 'S',
    summary: 'Ignore distracting nouns and make the verb agree with the true head subject.',
    strategy: ['Find the main subject.', 'Cross out prepositional phrases mentally.', 'Each/every/one/the number = singular.', 'With neither…nor, check the nearer subject.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('sva-1','subject-verb','Each of the conference rooms _____ equipped with a large display.',['are','is','have','be'],'B','The head subject is “Each.”','each of + plural noun → singular verb.','Even though “rooms” is plural, “Each” controls the verb, so “is” is correct.','The nearby plural noun “rooms” is the distractor.',2),
      e('sva-2','subject-verb','The results of the survey _____ encouraging.',['is','are','was','has'],'B','The head subject is “results.”','Plural head noun → plural verb.','“Of the survey” does not change the plural subject “results.”','“Survey” is closer to the blank but is inside a prepositional phrase.',1),
      e('sva-3','subject-verb','The number of online orders _____ increased this month.',['have','has','are','were'],'B','The head phrase is “The number.”','the number of + plural noun → singular verb.','“The number” is singular, so “has increased” is correct.','“Orders” is plural but does not control the verb.',3),
      e('sva-4','subject-verb','Neither the supervisor nor the technicians _____ available this afternoon.',['is','are','was','be'],'B','With neither…nor, look at the nearer noun “technicians.”','neither A nor B → verb usually agrees with nearer subject.','“Technicians” is plural, so “are” is correct.','Choosing “is” by focusing on “supervisor” ignores the nearer subject.',3),
      e('sva-5','subject-verb','One of the new interns _____ fluent in Japanese.',['are','is','have','be'],'B','The head subject is “One.”','one of + plural noun → singular verb.','The sentence is about one intern, so “is” is correct.','“Interns” is plural only because it follows “of.”',1),
    ],
  },
  {
    skill: 'passive',
    title: 'Passive Voice',
    shortTitle: 'Passive',
    icon: 'V',
    summary: 'Ask whether the subject performs the action or receives it.',
    strategy: ['Receiver of action → passive.', 'Passive = be + past participle.', 'With modals: modal + be + V3.', 'Perfect passive: has/have been + V3.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('pass-1','passive','All applications _____ before interviews are scheduled.',['review','are reviewed','reviewed','are reviewing'],'B','Applications receive the action.','present simple passive = am/is/are + V3.','The HR team reviews the applications, so from the applications’ perspective they “are reviewed.”','“Review” would require the applications to perform the action.',2),
      e('pass-2','passive','The equipment must _____ before it is returned to storage.',['inspect','be inspected','inspected','be inspecting'],'B','Modal “must” + receiver of action.','modal passive = modal + be + V3.','The equipment receives the inspection, so “must be inspected” is correct.','“Must inspected” is missing “be.”',2),
      e('pass-3','passive','The damaged units have already _____ by the supplier.',['replace','been replaced','replacing','been replace'],'B','Signal: “by the supplier” + present perfect.','present perfect passive = have/has been + V3.','The supplier performed the action on the units: “have been replaced.”','“Have replaced” would make the units the doer.',3),
      e('pass-4','passive','Several employees will _____ to the new branch next month.',['transfer','be transferred','transferred','be transferring'],'B','Employees receive the transfer action.','future passive = will be + V3.','The company will transfer them, so they “will be transferred.”','“Will transfer” would imply the employees transfer something else.',2),
      e('pass-5','passive','The computers _____ when the power outage occurred.',['were being updated','updated','have updated','are updating'],'A','An action was in progress and the computers received it.','past continuous passive = was/were being + V3.','The update was happening at the time of the outage, so “were being updated” fits.','Simple past does not express the ongoing background action.',4),
    ],
  },
  {
    skill: 'relative-clause',
    title: 'Relative Clauses',
    shortTitle: 'Relative Clauses',
    icon: 'R',
    summary: 'Match the relative word to the antecedent and to its role inside the clause.',
    strategy: ['Person subject → who.', 'Thing → which.', 'Possession → whose.', 'Place → where; formal object after preposition → whom.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('rel-1','relative-clause','The employee _____ organized the event received an award.',['which','who','whose','where'],'B','Antecedent = person; blank is subject of “organized.”','person + subject relative clause → who.','“Who” refers to the employee and performs “organized.”','“Whose” would need a following noun to show possession.',1),
      e('rel-2','relative-clause','The building _____ roof was damaged will remain closed.',['who','which','whose','where'],'C','The roof belongs to the building.','whose = possession for people or things.','“Whose roof” means “the building’s roof.”','“Which roof” would not form the required possessive relationship.',2),
      e('rel-3','relative-clause','The warehouse, _____ opened last year, is already at full capacity.',['who','which','where','what'],'B','Antecedent = thing; blank is subject of “opened.”','nonrestrictive thing clause → which.','“Which” correctly refers to the warehouse.','“Where” would require a clause describing something happening at that location.',2),
      e('rel-4','relative-clause','The city _____ the conference is held has expanded its convention center.',['which','where','who','whose'],'B','The city is the location of the conference.','place + clause describing activity there → where.','“Where” means “in which” here.','“Which” would need a preposition: “in which.”',2),
      e('rel-5','relative-clause','The consultant with _____ we met recommended another supplier.',['who','whom','which','whose'],'B','The relative word follows the preposition “with.”','formal object after preposition referring to person → whom.','“Whom” is the object of “with.”','“Who” is common informally, but TOEIC grammar questions often prefer the formal object form after a preposition.',4),
    ],
  },
  {
    skill: 'pronoun',
    title: 'Pronoun Forms',
    shortTitle: 'Pronouns',
    icon: 'O',
    summary: 'Choose subject, object, possessive adjective, possessive pronoun, or reflexive based on the blank’s job.',
    strategy: ['Before a noun → my/your/their/etc.', 'After a verb/preposition → object form.', 'Same subject and object → reflexive.', 'Standalone possession → mine/yours/theirs.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('pro-1','pronoun','Employees should keep _____ ID cards visible at all times.',['they','their','theirs','them'],'B','A noun follows the blank: “ID cards.”','Before a noun → possessive adjective.','“Their” modifies “ID cards.”','“Theirs” is a possessive pronoun and stands alone; it cannot directly modify a noun.',1),
      e('pro-2','pronoun','Managers should familiarize _____ with the updated policy.',['them','their','themselves','theirs'],'C','Managers are both the doer and receiver.','same subject and object → reflexive pronoun.','The managers familiarize themselves.','“Them” would usually refer to different people.',2),
      e('pro-3','pronoun','The revised proposal is more practical than _____ submitted last month.',['that','those','them','itself'],'A','Replace the singular noun “proposal” without repeating it.','that can substitute for a singular thing in a comparison.','“That” stands for “the proposal.”','“Those” would replace a plural noun.',3),
      e('pro-4','pronoun','The two designs are similar, but _____ is less expensive to manufacture.',['one','ones','themselves','each other'],'A','Choose one member of a pair.','one can replace one singular count noun from a known set.','“One” means one of the two designs.','“Ones” is plural.',2),
      e('pro-5','pronoun','The director thanked everyone _____ had helped with the launch.',['which','who','where','whose'],'B','“Everyone” refers to people and is the subject of “had helped.”','person as relative-clause subject → who.','“Who” connects the people to the action they performed.','“Whose” expresses possession, not subject function here.',2),
    ],
  },
  {
    skill: 'comparison',
    title: 'Comparisons',
    shortTitle: 'Comparisons',
    icon: '>',
    summary: 'Use comparison signals such as than, as…as, twice as, and of the three to choose the correct form.',
    strategy: ['than → comparative.', 'as + adjective + as.', 'Group of 3+ → superlative.', 'Long adjectives usually use more/most.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('cmp-1','comparison','This quarter’s sales were significantly _____ than expected.',['high','higher','highest','highly'],'B','Signal: “than.”','than → comparative form.','The comparative of “high” is “higher.”','“Highly” is an adverb, not the comparative adjective needed here.',1),
      e('cmp-2','comparison','The new office is not as spacious _____ the previous location.',['than','as','like','from'],'B','Pattern begins with “as.”','as + adjective + as.','The correct fixed structure is “as spacious as.”','“Than” follows comparative forms such as “more spacious than.”',1),
      e('cmp-3','comparison','Of the three proposals, the second is the _____ practical.',['more','most','much','very'],'B','Comparing one item with a group of three.','three or more → superlative.','“The most practical” is the correct superlative phrase.','“More” compares two items.',1),
      e('cmp-4','comparison','The new warehouse is nearly twice as large _____ the old one.',['than','as','like','from'],'B','Pattern: twice as + adjective + ___.','multipliers use twice/three times as + adjective + as.','“Twice as large as” is the standard structure.','“Than” would be used with “twice larger than,” which is not the target TOEIC pattern.',2),
      e('cmp-5','comparison','The updated software runs considerably _____ than the previous version.',['smooth','more smoothly','smoothest','smoothly more'],'B','Signal: “than”; the word modifies “runs.”','comparative adverb for longer adverbs → more + adverb.','“More smoothly” is the comparative adverb modifying “runs.”','“Smooth” is an adjective, not an adverb.',3),
    ],
  },
  {
    skill: 'collocation',
    title: 'Business Collocations',
    shortTitle: 'Collocations',
    icon: 'B',
    summary: 'Learn common TOEIC business words as chunks instead of translating one word at a time.',
    strategy: ['Memorize verb+noun pairs.', 'Notice adjective+preposition patterns.', 'Use the surrounding business context.', 'Add missed chunks to the review queue.'],
    practiceCount: 10,
    passScore: 8,
    workedExamples: [
      e('col-1','collocation','The company will _____ a customer survey next week.',['conduct','construct','contain','contact'],'A','Common phrase: ___ a survey.','conduct a survey = carry out a survey.','“Conduct” is the natural business verb used with “survey.”','“Construct” means build; it does not form the standard phrase here.',2),
      e('col-2','collocation','Please keep the receipt as _____ of purchase.',['proof','permission','advice','approval'],'A','Fixed phrase: ___ of purchase.','proof of purchase is a standard retail/business phrase.','The receipt demonstrates that a purchase occurred.','“Approval of purchase” means permission, which is a different idea.',1),
      e('col-3','collocation','The retailer plans to _____ a new loyalty program in November.',['launch','land','lend','lift'],'A','Business phrase: ___ a product/program.','launch = introduce/start publicly.','Companies “launch” products, services, campaigns, and programs.','“Land” can mean obtain a deal/job, but not introduce a program.',1),
      e('col-4','collocation','The board decided to _____ the decision until more data were available.',['postpone','preserve','predict','purchase'],'A','Meaning: delay something until later.','postpone a decision/meeting/event.','“Postpone” directly means delay.','“Preserve” means keep something in its existing condition.',2),
      e('col-5','collocation','The new campaign is intended to _____ brand awareness.',['raise','rise','arise','lifted'],'A','Fixed phrase: ___ awareness.','raise awareness; raise is transitive and takes an object.','“Raise brand awareness” is the standard collocation.','“Rise” is intransitive and cannot directly take “awareness” as an object.',2),
    ],
  },
]

export const lessonBySkill = Object.fromEntries(lessons.map(lesson => [lesson.skill, lesson])) as Partial<Record<SkillId, LessonDefinition>>
